//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
//
#define IDR_MINHOOK_DLL 101
// wool
#define IDR_WOOL_WHITE 201
#define IDR_WOOL_ORANGE 202
#define IDR_WOOL_MAGENTA 203
#define IDR_WOOL_LIGHTBLUE 204
#define IDR_WOOL_YELLOW 205
#define IDR_WOOL_LIME 206
#define IDR_WOOL_PINK 207
#define IDR_WOOL_GRAY 208
#define IDR_WOOL_SILVER 209
#define IDR_WOOL_CYAN 210
#define IDR_WOOL_PURPLE 211
#define IDR_WOOL_BLUE 212
#define IDR_WOOL_BROWN 213
#define IDR_WOOL_GREEN 214
#define IDR_WOOL_RED 215
#define IDR_WOOL_BLACK 216
// glass
#define IDR_GLASS_WHITE 217
#define IDR_GLASS_ORANGE 218
#define IDR_GLASS_MAGENTA 219
#define IDR_GLASS_LIGHTBLUE 220
#define IDR_GLASS_YELLOW 221
#define IDR_GLASS_LIME 222
#define IDR_GLASS_PINK 223
#define IDR_GLASS_GRAY 224
#define IDR_GLASS_SILVER 225
#define IDR_GLASS_CYAN 226
#define IDR_GLASS_PURPLE 227
#define IDR_GLASS_BLUE 228
#define IDR_GLASS_BROWN 229
#define IDR_GLASS_GREEN 230
#define IDR_GLASS_RED 231
#define IDR_GLASS_BLACK 232
#define IDR_GLASS 233
// plank
#define IDR_PLANKS_OAK 234
#define IDR_PLANKS_SPRUCE 235
#define IDR_PLANKS_BIRCH 236
#define IDR_PLANKS_JUNGLE 237
#define IDR_PLANKS_ACACIA 238
#define IDR_PLANKS_DARKOAK 239
// logs
#define IDR_LOG_OAK 240
#define IDR_LOG_SPRUCE 241
#define IDR_LOG_BIRCH 242
#define IDR_LOG_JUNGLE 243
#define IDR_LOG_ACACIA 244
#define IDR_LOG_DARKOAK 245

// special
#define IDR_OBSIDIAN 246
#define IDR_END_STONE 247
#define IDR_TERRACOTTA 248

// terracotta
#define IDR_TERRACOTTA_WHITE 249
#define IDR_TERRACOTTA_ORANGE 250
#define IDR_TERRACOTTA_MAGENTA 251
#define IDR_TERRACOTTA_LIGHTBLUE 252
#define IDR_TERRACOTTA_YELLOW 253
#define IDR_TERRACOTTA_LIME 254
#define IDR_TERRACOTTA_PINK 255
#define IDR_TERRACOTTA_GRAY 256
#define IDR_TERRACOTTA_SILVER 257
#define IDR_TERRACOTTA_CYAN 258
#define IDR_TERRACOTTA_PURPLE 259
#define IDR_TERRACOTTA_BLUE 260
#define IDR_TERRACOTTA_BROWN 261
#define IDR_TERRACOTTA_GREEN 262
#define IDR_TERRACOTTA_RED 263
#define IDR_TERRACOTTA_BLACK 264
#define IDR_DISCORD_DLL 265

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 266
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 1001
#define _APS_NEXT_SYMED_VALUE 101
#endif
#endif
