#include "injector.h"
#include <CommCtrl.h>
#pragma comment(lib, "Comctl32.lib")
#include "crash_dumps.h"
#include "log_tail.h"
#include "process_scan.h"
#include "settings.h"
#include "tray_icon.h"
#include "updater.h"
#include <commdlg.h>
#include <ShlObj.h>

#include "ovson_ui.h" // generated by slint_target_sources()
#include <slint.h>

#include <Windows.h>
#include <windowsx.h>
#include <shellapi.h>
#include <atomic>
#include <chrono>
#include <map>
#include <memory>
#include <mutex>
#include <set>
#include <string>
#include <thread>
#include <vector>

namespace {

constexpr int kPhaseIntro     = 0;
constexpr int kPhaseSlide     = 1;
constexpr int kPhaseMain      = 2;
constexpr int kPhaseInjecting = 3;
constexpr int kPhaseDone      = 4;
constexpr int kPhaseFailed    = 5;

struct LocalRow {
  bool selected = false;
  int  progress = 0;
  std::wstring stage;
  bool working = false;
  bool finishedOk = false;
  bool finishedFail = false;
};

std::wstring widen(const std::string &s) {
  if (s.empty()) return {};
  int n = MultiByteToWideChar(CP_UTF8, 0, s.data(), (int)s.size(), nullptr, 0);
  std::wstring w(n, L'\0');
  MultiByteToWideChar(CP_UTF8, 0, s.data(), (int)s.size(), w.data(), n);
  return w;
}
std::string narrow(const std::wstring &w) {
  if (w.empty()) return {};
  int n = WideCharToMultiByte(CP_UTF8, 0, w.data(), (int)w.size(),
                              nullptr, 0, nullptr, nullptr);
  std::string s(n, '\0');
  WideCharToMultiByte(CP_UTF8, 0, w.data(), (int)w.size(),
                      s.data(), n, nullptr, nullptr);
  return s;
}

struct AppState {
  std::mutex                                mtx;
  std::map<DWORD, LocalRow>                 local;
  std::vector<MinecraftProcess>             processes;
  std::atomic<int>                          phase{kPhaseIntro};
  std::shared_ptr<slint::VectorModel<PRow>> model;
  std::set<DWORD>                           autoInjectAttempted;
  std::atomic<bool>                         autoInjectEnabled{false};
};

template <class F> void onUiThread(F &&f) {
  slint::invoke_from_event_loop(std::forward<F>(f));
}

void publishProcesses(const MainWindow &ui, AppState &state) {
  std::lock_guard<std::mutex> lk(state.mtx);

  int anyWorking = 0;
  int anyDone = 0;
  int anyFail = 0;
  int selected = 0;
  std::vector<PRow> targetRows;
  for (const auto &mp : state.processes) {
    LocalRow &lr = state.local[mp.pid];
    if (mp.injected) {
      lr.selected = false;
      if (!lr.finishedFail) lr.finishedOk = true;
    } else {
      lr.finishedOk = false;
    }
    PRow r;
    r.pid = (int)mp.pid;
    r.title = slint::SharedString(narrow(mp.windowTitle));
    r.selected = lr.selected && !mp.injected;
    r.injected = mp.injected;
    r.progress = lr.progress;
    r.stage = slint::SharedString(narrow(lr.stage));
    r.working = lr.working;
    r.finished_ok = lr.finishedOk;
    r.finished_fail = lr.finishedFail;

    r.launcher_label = slint::SharedString(launcherLabel(mp.launcher));
    {
      uint32_t argb = launcherColor(mp.launcher);
      uint8_t a = (argb >> 24) & 0xFF;
      uint8_t cr = (argb >> 16) & 0xFF;
      uint8_t cg = (argb >> 8) & 0xFF;
      uint8_t cb = argb & 0xFF;
      r.launcher_color = slint::Color::from_argb_uint8(a, cr, cg, cb);
    }
    r.mc_version = slint::SharedString(narrow(mp.mcVersion));

    if (mp.privateMemBytes >= (1ULL << 30)) {
      char buf[24];
      double gb = (double)mp.privateMemBytes / (1ULL << 30);
      snprintf(buf, sizeof(buf), "%.1f GB", gb);
      r.memory_text = slint::SharedString(buf);
    } else if (mp.privateMemBytes >= (1ULL << 20)) {
      char buf[24];
      uint64_t mb = mp.privateMemBytes / (1ULL << 20);
      snprintf(buf, sizeof(buf), "%llu MB", (unsigned long long)mb);
      r.memory_text = slint::SharedString(buf);
    } else {
      r.memory_text = slint::SharedString("");
    }

    if (mp.uptimeSeconds >= 60) {
      char buf[24];
      uint32_t mins  = mp.uptimeSeconds / 60;
      uint32_t hours = mins / 60;
      mins %= 60;
      if (hours > 0)  snprintf(buf, sizeof(buf), "%uh %um", hours, mins);
      else            snprintf(buf, sizeof(buf), "%um", mins);
      r.uptime_text = slint::SharedString(buf);
    } else {
      r.uptime_text = slint::SharedString("");
    }

    targetRows.push_back(r);
    if (lr.working) anyWorking++;
    if (lr.finishedOk) anyDone++;
    if (lr.finishedFail) anyFail++;
    if (r.selected) selected++;
  }

  if (state.model) {
    size_t currentCount = state.model->row_count();
    size_t targetCount = targetRows.size();
    if (currentCount != targetCount) {
      state.model->clear();
      for (const auto &r : targetRows) {
        state.model->push_back(r);
      }
    } else {
      for (size_t i = 0; i < targetCount; ++i) {
        auto optRow = state.model->row_data(i);
        if (optRow) {
          const PRow &existing = *optRow;
          const PRow &target = targetRows[i];
          if (existing.pid != target.pid ||
              existing.title != target.title ||
              existing.selected != target.selected ||
              existing.injected != target.injected ||
              existing.progress != target.progress ||
              existing.stage != target.stage ||
              existing.working != target.working ||
              existing.finished_ok != target.finished_ok ||
              existing.finished_fail != target.finished_fail ||
              existing.launcher_label != target.launcher_label ||
              existing.mc_version != target.mc_version ||
              existing.memory_text != target.memory_text ||
              existing.uptime_text != target.uptime_text) {
            state.model->set_row_data(i, target);
          }
        }
      }
    }
  }

  ui.set_selected_count(selected);

  int phase = state.phase.load();
  if (phase == kPhaseInjecting && anyWorking == 0) {
    if (anyFail > 0 && anyDone == 0)      phase = kPhaseFailed;
    else if (anyFail > 0)                 phase = kPhaseFailed;
    else                                  phase = kPhaseDone;
    state.phase.store(phase);
    ui.set_phase(phase);
  } else if ((phase == kPhaseDone || phase == kPhaseFailed) && selected > 0) {
    phase = kPhaseMain;
    state.phase.store(phase);
    ui.set_phase(phase);
  } else if ((phase == kPhaseDone || phase == kPhaseFailed || phase == kPhaseInjecting) && anyWorking == 0 && anyDone == 0 && anyFail == 0) {
    phase = kPhaseMain;
    state.phase.store(phase);
    ui.set_phase(phase);
  }

  bool anyUninjectFail = false;
  std::wstring failStage;
  for (const auto &mp : state.processes) {
    auto it = state.local.find(mp.pid);
    if (it != state.local.end() && it->second.finishedFail && mp.injected) {
      anyUninjectFail = true;
      failStage = it->second.stage;
      break;
    }
  }

  std::string status;
  if (anyUninjectFail) {
    if (failStage.find(L"event missing") != std::wstring::npos) {
      if (!embeddedDllHasUninjectHandler()) {
        status = "Uninject failed: embedded OVson.dll is the OLD one "
                 "(no uninject handler). The loader's .rc resource was "
                 "NOT refreshed during rebuild — delete OVsonLoader's "
                 "build folder and rebuild from scratch.";
      } else {
        status = "Uninject failed: embedded DLL has the handler, but "
                 "the running process didn't load it. Close ALL Minecraft "
                 "instances (Task Manager) and re-inject with this loader.";
      }
    } else if (failStage.find(L"access denied") != std::wstring::npos) {
      status = "Uninject failed: access denied to the uninject event. "
               "Run the loader with the same user as Minecraft.";
    } else {
      status = std::string("Uninject failed: ") + narrow(failStage);
    }
  } else switch (state.phase.load()) {
    case kPhaseDone:      status = "Injection complete";           break;
    case kPhaseFailed:    status = "Some instances failed to inject"; break;
    case kPhaseInjecting: status = "Injecting…";                   break;
    default:
      if (state.processes.empty()) {
        status = "Waiting for Minecraft to launch";
      } else {
        int sel = 0;
        for (const auto &mp : state.processes)
          if (!mp.injected && state.local[mp.pid].selected) sel++;
        if (sel == 0) status = "Select an instance to inject into";
        else if (sel == 1) status = "Ready to inject";
        else { char b[64]; snprintf(b, 64, "Ready to inject %d instances", sel); status = b; }
      }
      break;
  }
  ui.set_status_text(slint::SharedString(status));
}

LRESULT CALLBACK SubclassProc(HWND hWnd, UINT uMsg, WPARAM wParam,
                               LPARAM lParam, UINT_PTR, DWORD_PTR) {
  if (uMsg == WM_NCHITTEST) {
    LRESULT hit = DefSubclassProc(hWnd, uMsg, wParam, lParam);
    if (hit == HTCLIENT) {
      POINT pt = { GET_X_LPARAM(lParam), GET_Y_LPARAM(lParam) };
      ScreenToClient(hWnd, &pt);
      RECT rc;
      GetClientRect(hWnd, &rc);
      int navHoleW = 440;
      int navStart = (rc.right - navHoleW) / 2;
      int navEnd   = navStart + navHoleW;
      bool inNavHole = (pt.x >= navStart && pt.x <= navEnd);
      if (pt.y < 48 && pt.x < (rc.right - 48) && !inNavHole) {
        return HTCAPTION;
      }
    }
    return hit;
  }
  if (uMsg == WM_MOUSEACTIVATE) {
    return MA_ACTIVATE;
  }
  return DefSubclassProc(hWnd, uMsg, wParam, lParam);
}

} // namespace

int APIENTRY wWinMain(HINSTANCE, HINSTANCE, LPWSTR, int) {
  HRSRC resSlint = FindResourceW(nullptr, MAKEINTRESOURCEW(2), RT_RCDATA);
  if (resSlint) {
    HGLOBAL hSlint = LoadResource(nullptr, resSlint);
    DWORD szSlint = SizeofResource(nullptr, resSlint);
    void* dataSlint = LockResource(hSlint);
    if (dataSlint && szSlint > 0) {
      wchar_t tempPath[MAX_PATH];
      GetTempPathW(MAX_PATH, tempPath);
      std::wstring dllPath = std::wstring(tempPath) + L"slint_cpp.dll";
      HANDLE hFile = CreateFileW(dllPath.c_str(), GENERIC_WRITE, 0, nullptr, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
      if (hFile != INVALID_HANDLE_VALUE) {
        DWORD written = 0;
        WriteFile(hFile, dataSlint, szSlint, &written, nullptr);
        CloseHandle(hFile);
      }
      LoadLibraryW(dllPath.c_str());
    }
  }


  auto &dll = embeddedDllBytes();
  bool payloadOk = !dll.empty();

  AppState state;
  state.model = std::make_shared<slint::VectorModel<PRow>>();
  auto ui = MainWindow::create();
  ui->set_processes(state.model);

  Settings::Values prefs = Settings::load();
  ui->set_setting_auto_inject(prefs.autoInject);
  ui->set_setting_start_with_windows(prefs.startWithWindows);
  ui->set_setting_minimize_to_tray(prefs.minimizeToTray);
  ui->set_setting_auto_check_updates(prefs.autoCheckUpdates);
  ui->set_setting_dll_slot(prefs.dllSlot);
  ui->set_setting_custom_dll_path(
      slint::SharedString(narrow(prefs.customDllPath)));
  setActiveSlot(prefs.dllSlot, prefs.customDllPath);
  state.autoInjectEnabled.store(prefs.autoInject);

  auto logModel = std::make_shared<slint::VectorModel<LogLine>>();
  ui->set_log_lines(logModel);

  static LogTail s_tail;

  ui->on_open_log_folder([]() {
    wchar_t appData[MAX_PATH] = L"";
    if (SUCCEEDED(SHGetFolderPathW(nullptr, CSIDL_LOCAL_APPDATA,
                                    nullptr, SHGFP_TYPE_CURRENT,
                                    appData))) {
      std::wstring dir = std::wstring(appData) + L"\\OVson\\logs";
      CreateDirectoryW(dir.c_str(), nullptr);
      ShellExecuteW(nullptr, L"open", dir.c_str(), nullptr, nullptr,
                    SW_SHOWNORMAL);
    }
  });
  ui->on_clear_log([logModel, uiHandle = ui]() {
    logModel->clear();
    uiHandle->set_log_path(slint::SharedString(""));
  });

  {
    auto dumps = CrashDumps::scan();
    ui->set_dump_count((int)dumps.size());
  }
  ui->on_open_dumps_folder([]() {
    CrashDumps::openInExplorer(L"");
  });
  ui->on_dismiss_crash_dumps([uiHandle = ui]() {
    uiHandle->set_dump_count(0);
  });
  ui->on_report_modal_yes([]() {
    CrashDumps::openInExplorer(L"");
    ShellExecuteW(nullptr, L"open",
                  L"https://github.com/alperenproo/ovson/issues/new"
                  L"?labels=crash&template=crash.md",
                  nullptr, nullptr, SW_SHOWNORMAL);
  });
  ui->on_report_modal_no([uiHandle = ui]() {
    int n = CrashDumps::deleteAll();
    uiHandle->set_dump_count(0);
    char msg[96];
    sprintf_s(msg, "Removed %d dump file%s.", n, n == 1 ? "" : "s");
    uiHandle->set_status_text(slint::SharedString(msg));
  });

  ui->on_settings_changed([uiHandle = ui, &state]() {
    Settings::Values v;
    v.autoInject       = uiHandle->get_setting_auto_inject();
    v.startWithWindows = uiHandle->get_setting_start_with_windows();
    v.minimizeToTray   = uiHandle->get_setting_minimize_to_tray();
    v.autoCheckUpdates = uiHandle->get_setting_auto_check_updates();
    v.dllSlot          = uiHandle->get_setting_dll_slot();
    v.customDllPath    = widen(std::string(
        uiHandle->get_setting_custom_dll_path().data()));
    Settings::save(v);
    setActiveSlot(v.dllSlot, v.customDllPath);
    state.autoInjectEnabled.store(v.autoInject);

    if (v.autoCheckUpdates) {
      if (uiHandle->get_update_state() == 0) {
        uiHandle->set_update_state(1);
        uiHandle->set_update_available(true);
        Updater::startCheck();
      }
    } else {
      uiHandle->set_update_state(0);
      uiHandle->set_update_available(false);
    }
  });

  ui->on_pick_custom_dll([uiHandle = ui]() {
    wchar_t file[MAX_PATH] = L"";
    OPENFILENAMEW ofn{};
    ofn.lStructSize  = sizeof(ofn);
    ofn.lpstrFilter  = L"OVson DLL (*.dll)\0*.dll\0All files\0*.*\0";
    ofn.lpstrFile    = file;
    ofn.nMaxFile     = MAX_PATH;
    ofn.lpstrTitle   = L"Select custom OVson.dll";
    ofn.Flags        = OFN_FILEMUSTEXIST | OFN_HIDEREADONLY
                       | OFN_PATHMUSTEXIST | OFN_NOCHANGEDIR;
    if (GetOpenFileNameW(&ofn) && file[0] != L'\0') {
      uiHandle->set_setting_custom_dll_path(
          slint::SharedString(narrow(file)));
      Settings::Values v;
      v.autoInject       = uiHandle->get_setting_auto_inject();
      v.startWithWindows = uiHandle->get_setting_start_with_windows();
      v.minimizeToTray   = uiHandle->get_setting_minimize_to_tray();
      v.autoCheckUpdates = uiHandle->get_setting_auto_check_updates();
      v.dllSlot          = uiHandle->get_setting_dll_slot();
      v.customDllPath    = file;
      Settings::save(v);
      setActiveSlot(v.dllSlot, v.customDllPath);
    }
  });

  publishProcesses(*ui, state);
  std::thread([uiHandle = ui]() mutable {
    int lastPct = -1;
    Updater::State lastState = Updater::State::Idle;
    bool upToDateDismissScheduled = false;
    bool failedDismissScheduled = false;
    for (;;) {
      auto st = Updater::currentState();
      int pct = Updater::downloadPct();
      if (st != lastState || pct != lastPct) {
        lastState = st;
        lastPct = pct;
        std::string statusText;
        std::string versionText = "v" + Updater::info().remoteVersion;
        int stateCode = 1; // checking by default
        int progress = 0;
        bool legacyAvailable = false;
        switch (st) {
          case Updater::State::Idle:
            stateCode = 1; break;
          case Updater::State::Checking:
            stateCode = 1; break;
          case Updater::State::UpToDate:
            stateCode = 2; statusText = "Up to date";
            versionText = "v" + std::string(Updater::kBuildVersion);
            break;
          case Updater::State::UpdateAvailable:
            stateCode = 3; legacyAvailable = true;
            statusText = "Update available";
            break;
          case Updater::State::Downloading:
            stateCode = 4; legacyAvailable = true;
            progress = pct; statusText = "Downloading…";
            break;
          case Updater::State::Ready:
            stateCode = 5; legacyAvailable = true;
            progress = 100; statusText = "Ready";
            break;
          case Updater::State::Failed:
            stateCode = 6; statusText = Updater::lastError();
            if (statusText.empty()) statusText = "Update check failed";
            break;
        }
        slint::invoke_from_event_loop(
            [uiHandle, stateCode, statusText, versionText,
             legacyAvailable, progress]() {
              uiHandle->set_update_state(stateCode);
              uiHandle->set_update_available(legacyAvailable);
              uiHandle->set_update_version(slint::SharedString(versionText));
              uiHandle->set_update_status(slint::SharedString(statusText));
              uiHandle->set_update_progress(progress);
            });

        if (stateCode == 2 && !upToDateDismissScheduled) {
          upToDateDismissScheduled = true;
          std::thread([uiHandle]() mutable {
            std::this_thread::sleep_for(std::chrono::milliseconds(2200));
            slint::invoke_from_event_loop([uiHandle]() {
              uiHandle->set_update_state(0);
              uiHandle->set_update_available(false);
            });
          }).detach();
        }
        if (stateCode != 6) failedDismissScheduled = false;
        if (stateCode == 6 && !failedDismissScheduled) {
          failedDismissScheduled = true;
          std::thread([uiHandle]() mutable {
            std::this_thread::sleep_for(std::chrono::milliseconds(6000));
            slint::invoke_from_event_loop([uiHandle]() {
              if (uiHandle->get_update_state() == 6) {
                uiHandle->set_update_state(0);
                uiHandle->set_update_available(false);
              }
            });
          }).detach();
        }
      }
      std::this_thread::sleep_for(std::chrono::milliseconds(250));
    }
  }).detach();

  std::thread([uiHandle = ui, &state]() {
    auto sleep = [](int ms) {
      std::this_thread::sleep_for(std::chrono::milliseconds(ms));
    };
    sleep(800);  // hold the centered logo
    onUiThread([uiHandle, &state]() {
      state.phase.store(kPhaseSlide);
      uiHandle->set_phase(kPhaseSlide);
    });
    sleep(950);
    onUiThread([uiHandle, &state]() {
      state.phase.store(kPhaseMain);
      uiHandle->set_phase(kPhaseMain);
      if (uiHandle->get_setting_auto_check_updates()) {
        uiHandle->set_update_state(1);
        uiHandle->set_update_available(true);
        Updater::startCheck();
      } else {
        uiHandle->set_update_state(0);
        uiHandle->set_update_available(false);
      }
    });
  }).detach();

  std::atomic<bool> stopScan{false};
  std::thread scanThread([uiHandle = ui, &state, &stopScan]() mutable {
    while (!stopScan.load()) {
      auto latest = findMinecraftProcesses();
      bool shouldAutoInject = false;
      {
        std::lock_guard<std::mutex> lk(state.mtx);
        state.processes = std::move(latest);
        for (auto it = state.local.begin(); it != state.local.end();) {
          bool present = false;
          for (const auto &mp : state.processes)
            if (mp.pid == it->first) { present = true; break; }
          if (!present) it = state.local.erase(it);
          else ++it;
        }
        for (auto it = state.autoInjectAttempted.begin();
             it != state.autoInjectAttempted.end();) {
          bool present = false;
          for (const auto &mp : state.processes)
            if (mp.pid == *it) { present = true; break; }
          if (!present) it = state.autoInjectAttempted.erase(it);
          else ++it;
        }
        if (state.phase.load() == kPhaseMain &&
            state.autoInjectEnabled.load()) {
          for (const auto &mp : state.processes) {
            if (mp.injected) continue;
            if (state.autoInjectAttempted.count(mp.pid)) continue;
            state.local[mp.pid].selected = true;
            state.autoInjectAttempted.insert(mp.pid);
            shouldAutoInject = true;
          }
        }
      }
      onUiThread([uiHandle, &state, shouldAutoInject]() mutable {
        publishProcesses(*uiHandle, state);
        if (shouldAutoInject) {
          uiHandle->invoke_inject_clicked();
        }
      });
      std::this_thread::sleep_for(std::chrono::milliseconds(500));
    }
  });

  static std::atomic<bool> s_trayBalloonShown{false};
  ui->on_close_clicked([uiHandle = ui]() mutable {
    if (!uiHandle->get_setting_minimize_to_tray()) {
      slint::quit_event_loop();
      return;
    }
    HWND hwnd = FindWindowW(nullptr, L"OVson");
    if (hwnd) ShowWindow(hwnd, SW_HIDE);
    if (!s_trayBalloonShown.exchange(true)) {
      Tray::notify(L"OVson",
                   L"Running in the system tray. "
                   L"Right-click the icon to quit.");
    }
  });

  ui->set_build_version(slint::SharedString(Updater::kBuildVersion));
  ui->on_open_github([]() {
    ShellExecuteW(nullptr, L"open",
                  L"https://github.com/alperenproo/ovson", nullptr,
                  nullptr, SW_SHOWNORMAL);
  });
  ui->on_view_changelog([]() {
    ShellExecuteW(nullptr, L"open",
                  L"https://github.com/alperenproo/ovson/releases/latest",
                  nullptr, nullptr, SW_SHOWNORMAL);
  });

  ui->on_install_update([uiHandle = ui]() mutable {
    auto st = Updater::currentState();
    if (st == Updater::State::UpdateAvailable) {
      Updater::startDownload();
    } else if (st == Updater::State::Ready) {
      if (Updater::installAndRelaunch())
        slint::quit_event_loop();
    }
  });
  ui->on_toggle_row([&](int idx) {
    {
      std::lock_guard<std::mutex> lk(state.mtx);
      if (idx < 0 || idx >= (int)state.processes.size()) return;
      auto &mp = state.processes[idx];
      if (mp.injected) return;
      auto &lr = state.local[mp.pid];
      lr.selected = !lr.selected;
    }
    publishProcesses(*ui, state);
  });
  ui->on_show_context_menu([&state, uiHandle = ui](int idx) {
    DWORD pid = 0;
    bool injected = false;
    bool selected = false;
    std::wstring exePath;
    {
      std::lock_guard<std::mutex> lk(state.mtx);
      if (idx < 0 || idx >= (int)state.processes.size()) return;
      const auto &mp = state.processes[idx];
      pid      = mp.pid;
      injected = mp.injected;
      auto it  = state.local.find(pid);
      if (it != state.local.end()) selected = it->second.selected;
      exePath  = mp.exePath;
    }

    enum : UINT {
      ID_TOGGLE      = 5001,
      ID_UNINJECT    = 5002,
      ID_COPY_PID    = 5003,
      ID_OPEN_FOLDER = 5004,
      ID_KILL        = 5005,
    };

    HWND hwnd = FindWindowW(nullptr, L"OVson");
    if (!hwnd) return;
    HMENU menu = CreatePopupMenu();
    if (!menu) return;

    if (injected) {
      AppendMenuW(menu, MF_STRING, ID_UNINJECT, L"Uninject");
    } else {
      AppendMenuW(menu, MF_STRING, ID_TOGGLE,
                  selected ? L"Deselect" : L"Select for injection");
    }
    AppendMenuW(menu, MF_SEPARATOR, 0, nullptr);
    AppendMenuW(menu, MF_STRING, ID_COPY_PID, L"Copy PID");
    AppendMenuW(menu, MF_STRING | (exePath.empty() ? MF_GRAYED : 0),
                ID_OPEN_FOLDER, L"Open game folder");
    AppendMenuW(menu, MF_SEPARATOR, 0, nullptr);
    AppendMenuW(menu, MF_STRING, ID_KILL, L"Kill process…");

    POINT pt;
    GetCursorPos(&pt);
    SetForegroundWindow(hwnd);
    UINT cmd = TrackPopupMenu(menu,
                              TPM_RETURNCMD | TPM_RIGHTBUTTON
                                | TPM_NONOTIFY,
                              pt.x, pt.y, 0, hwnd, nullptr);
    DestroyMenu(menu);

    switch (cmd) {
      case ID_TOGGLE:
        uiHandle->invoke_toggle_row(idx);
        break;
      case ID_UNINJECT:
        uiHandle->invoke_uninject_row(idx);
        break;
      case ID_COPY_PID: {
        wchar_t buf[16];
        wsprintfW(buf, L"%lu", (unsigned long)pid);
        if (OpenClipboard(hwnd)) {
          EmptyClipboard();
          size_t bytes = (wcslen(buf) + 1) * sizeof(wchar_t);
          HGLOBAL mem = GlobalAlloc(GMEM_MOVEABLE, bytes);
          if (mem) {
            void *p = GlobalLock(mem);
            if (p) {
              memcpy(p, buf, bytes);
              GlobalUnlock(mem);
              SetClipboardData(CF_UNICODETEXT, mem);
            } else {
              GlobalFree(mem);
            }
          }
          CloseClipboard();
        }
        break;
      }
      case ID_OPEN_FOLDER: {
        if (exePath.empty()) break;
        std::wstring arg = L"/select,\"" + exePath + L"\"";
        ShellExecuteW(nullptr, L"open", L"explorer.exe", arg.c_str(),
                      nullptr, SW_SHOWNORMAL);
        break;
      }
      case ID_KILL: {
        if (MessageBoxW(hwnd,
                        L"Kill this Minecraft process? Any unsaved "
                        L"progress will be lost.",
                        L"OVson — Kill process",
                        MB_ICONWARNING | MB_YESNO | MB_DEFBUTTON2)
            == IDYES) {
          HANDLE h = OpenProcess(PROCESS_TERMINATE, FALSE, pid);
          if (h) {
            TerminateProcess(h, 1);
            CloseHandle(h);
          }
        }
        break;
      }
      default: break;
    }
  });

  ui->on_uninject_row([&](int idx) {
    DWORD pid = 0;
    {
      std::lock_guard<std::mutex> lk(state.mtx);
      if (idx < 0 || idx >= (int)state.processes.size()) return;
      auto &mp = state.processes[idx];
      if (!mp.injected) return;
      pid = mp.pid;
      auto &lr = state.local[pid];
      lr.working = true;
      lr.finishedFail = false;
      lr.finishedOk = false;
      lr.stage = L"Uninjecting";
      lr.progress = 50;
    }
    publishProcesses(*ui, state);

    std::thread([uiHandle = ui, &state, pid]() {
      DWORD err = 0;
      bool ok = uninjectPid(pid, &err);
      {
        std::lock_guard<std::mutex> lk(state.mtx);
        auto &lr = state.local[pid];
        lr.selected = false;
        lr.finishedOk = false;
        lr.finishedFail = !ok;
        lr.working = false;
        lr.progress = ok ? 0 : 100;
        if (ok) {
          lr.stage.clear();
        } else {
          wchar_t buf[96];
          const wchar_t *kind =
              err == 2  ? L"event missing"
            : err == 5  ? L"access denied"
                        : L"err";
          wsprintfW(buf, L"Uninject failed (%s, %lu)", kind, err);
          lr.stage = buf;
        }
        if (ok) {
          for (auto &mp : state.processes) {
            if (mp.pid == pid) {
              mp.injected = false;
              break;
            }
          }
        }
      }
      onUiThread([uiHandle, &state]() mutable {
        publishProcesses(*uiHandle, state);
      });
    }).detach();
  });
  ui->on_inject_clicked([&]() {
    if (!payloadOk) return;
    std::vector<DWORD> targets;
    {
      std::lock_guard<std::mutex> lk(state.mtx);
      for (auto &kv : state.local) {
        kv.second.finishedFail = false;
        if (!kv.second.working) kv.second.stage.clear();
      }
      for (const auto &mp : state.processes) {
        auto &lr = state.local[mp.pid];
        if (lr.selected && !mp.injected) {
          targets.push_back(mp.pid);
          lr.working = true;
          lr.finishedOk = false;
          lr.finishedFail = false;
          lr.progress = 1;
          lr.stage = L"Starting";
        }
      }
      if (targets.empty()) return;
      state.phase.store(kPhaseInjecting);
    }
    ui->set_phase(kPhaseInjecting);
    publishProcesses(*ui, state);

    for (DWORD pid : targets) {
      std::thread([uiHandle = ui, &state, pid]() mutable {
        auto progress = [uiHandle, &state, pid](int pct,
                                                const std::wstring &stage) mutable {
          {
            std::lock_guard<std::mutex> lk(state.mtx);
            auto &lr = state.local[pid];
            lr.progress = pct;
            lr.stage = stage;
          }
          onUiThread([uiHandle, &state]() mutable {
            publishProcesses(*uiHandle, state);
          });
        };
        bool ok = injectPid(pid, progress);
        {
          std::lock_guard<std::mutex> lk(state.mtx);
          auto &lr = state.local[pid];
          lr.working = false;
          if (ok) {
            lr.finishedOk = true;
            lr.selected = false;
            for (auto &mp : state.processes) {
              if (mp.pid == pid) {
                mp.injected = true;
                break;
              }
            }
          }
          else    lr.finishedFail = true;
          lr.progress = 100;
        }
        onUiThread([uiHandle, &state]() mutable {
          publishProcesses(*uiHandle, state);
        });
      }).detach();
    }
  });

  if (!payloadOk) {
    state.phase.store(kPhaseFailed);
    ui->set_phase(kPhaseFailed);
    ui->set_status_text(slint::SharedString(
        "Payload missing — please reinstall the loader."));
  }

  ui->show();

  slint::invoke_from_event_loop([]() {
    HWND hwnd = FindWindowW(nullptr, L"OVson");
    if (!hwnd) hwnd = GetActiveWindow();
    if (!hwnd) hwnd = GetForegroundWindow();
    if (hwnd) {
      SetWindowSubclass(hwnd, SubclassProc, 1, 0);

      Tray::install(
          hwnd,
          /*onShow=*/[hwnd]() {
            ShowWindow(hwnd, SW_SHOW);
            ShowWindow(hwnd, SW_RESTORE);
            SetForegroundWindow(hwnd);
          },
          /*onQuit=*/[]() { slint::quit_event_loop(); });

      int screenWidth = GetSystemMetrics(SM_CXSCREEN);
      int screenHeight = GetSystemMetrics(SM_CYSCREEN);
      RECT rc;
      GetWindowRect(hwnd, &rc);
      int wWidth = rc.right - rc.left;
      int wHeight = rc.bottom - rc.top;
      int x = (screenWidth - wWidth) / 2;
      int y = (screenHeight - wHeight) / 2;
      SetWindowPos(hwnd, nullptr, x, y, 0, 0, SWP_NOZORDER | SWP_NOSIZE | SWP_NOACTIVATE);
    }
  });

  slint::invoke_from_event_loop([uiHandle = ui, logModel]() mutable {
    s_tail.start(
        L"",
        [uiHandle, logModel](const std::string &line) {
          slint::Color colour =
              slint::Color::from_argb_uint8(0xFF, 0xA1, 0xA1, 0xAA);
          if (line.find("[ERROR]") != std::string::npos) {
            colour = slint::Color::from_argb_uint8(0xFF, 0xEF, 0x44, 0x44);
          } else if (line.find("[INFO]") != std::string::npos) {
            colour = slint::Color::from_argb_uint8(0xFF, 0x5e, 0xea, 0xd4);
          } else if (line.find("[CHAT]") != std::string::npos) {
            colour = slint::Color::from_argb_uint8(0xFF, 0xF6, 0xF7, 0xFA);
          }
          LogLine row;
          row.text  = slint::SharedString(line);
          row.color = colour;
          slint::invoke_from_event_loop(
              [logModel, row, uiHandle]() mutable {
                logModel->push_back(row);
                while (logModel->row_count() > 500) {
                  logModel->erase(0);
                }
              });
        },
        [uiHandle, logModel](const std::wstring &newPath) {
          slint::invoke_from_event_loop(
              [uiHandle, logModel, newPath]() mutable {
                logModel->clear();
                uiHandle->set_log_path(
                    slint::SharedString(narrow(newPath)));
              });
        });
  });

  slint::run_event_loop();

  stopScan.store(true);
  if (scanThread.joinable()) scanThread.join();
  s_tail.stop();
  Tray::uninstall();
  return 0;
}
