#include "injector.h"
#include <CommCtrl.h>
#pragma comment(lib, "Comctl32.lib")
#include "process_scan.h"
#include "updater.h"

#include "ovson_ui.h" // generated by slint_target_sources()
#include <slint.h>

#include <Windows.h>
#include <windowsx.h>
#include <atomic>
#include <chrono>
#include <map>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <vector>

namespace {

constexpr int kPhaseIntro     = 0;
constexpr int kPhaseSlide     = 1;
constexpr int kPhaseMain      = 2;
constexpr int kPhaseInjecting = 3;
constexpr int kPhaseDone      = 4;
constexpr int kPhaseFailed    = 5;

struct LocalRow {
  bool selected = false;
  int  progress = 0;
  std::wstring stage;
  bool working = false;
  bool finishedOk = false;
  bool finishedFail = false;
};

std::wstring widen(const std::string &s) {
  if (s.empty()) return {};
  int n = MultiByteToWideChar(CP_UTF8, 0, s.data(), (int)s.size(), nullptr, 0);
  std::wstring w(n, L'\0');
  MultiByteToWideChar(CP_UTF8, 0, s.data(), (int)s.size(), w.data(), n);
  return w;
}
std::string narrow(const std::wstring &w) {
  if (w.empty()) return {};
  int n = WideCharToMultiByte(CP_UTF8, 0, w.data(), (int)w.size(),
                              nullptr, 0, nullptr, nullptr);
  std::string s(n, '\0');
  WideCharToMultiByte(CP_UTF8, 0, w.data(), (int)w.size(),
                      s.data(), n, nullptr, nullptr);
  return s;
}

struct AppState {
  std::mutex                                mtx;
  std::map<DWORD, LocalRow>                 local;
  std::vector<MinecraftProcess>             processes;
  std::atomic<int>                          phase{kPhaseIntro};
  std::shared_ptr<slint::VectorModel<PRow>> model;
};

template <class F> void onUiThread(F &&f) {
  slint::invoke_from_event_loop(std::forward<F>(f));
}

void publishProcesses(const MainWindow &ui, AppState &state) {
  std::lock_guard<std::mutex> lk(state.mtx);

  int anyWorking = 0;
  int anyDone = 0;
  int anyFail = 0;
  int selected = 0;
  std::vector<PRow> targetRows;
  for (const auto &mp : state.processes) {
    LocalRow &lr = state.local[mp.pid];
    if (mp.injected) {
      lr.selected = false;
      if (!lr.finishedFail) lr.finishedOk = true;
    } else {
      lr.finishedOk = false;
    }
    PRow r;
    r.pid = (int)mp.pid;
    r.title = slint::SharedString(narrow(mp.windowTitle));
    r.selected = lr.selected && !mp.injected;
    r.injected = mp.injected;
    r.progress = lr.progress;
    r.stage = slint::SharedString(narrow(lr.stage));
    r.working = lr.working;
    r.finished_ok = lr.finishedOk;
    r.finished_fail = lr.finishedFail;
    targetRows.push_back(r);
    if (lr.working) anyWorking++;
    if (lr.finishedOk) anyDone++;
    if (lr.finishedFail) anyFail++;
    if (r.selected) selected++;
  }

  if (state.model) {
    size_t currentCount = state.model->row_count();
    size_t targetCount = targetRows.size();
    if (currentCount != targetCount) {
      state.model->clear();
      for (const auto &r : targetRows) {
        state.model->push_back(r);
      }
    } else {
      for (size_t i = 0; i < targetCount; ++i) {
        auto optRow = state.model->row_data(i);
        if (optRow) {
          const PRow &existing = *optRow;
          const PRow &target = targetRows[i];
          if (existing.pid != target.pid ||
              existing.title != target.title ||
              existing.selected != target.selected ||
              existing.injected != target.injected ||
              existing.progress != target.progress ||
              existing.stage != target.stage ||
              existing.working != target.working ||
              existing.finished_ok != target.finished_ok ||
              existing.finished_fail != target.finished_fail) {
            state.model->set_row_data(i, target);
          }
        }
      }
    }
  }

  ui.set_selected_count(selected);

  int phase = state.phase.load();
  if (phase == kPhaseInjecting && anyWorking == 0) {
    if (anyFail > 0 && anyDone == 0)      phase = kPhaseFailed;
    else if (anyFail > 0)                 phase = kPhaseFailed;
    else                                  phase = kPhaseDone;
    state.phase.store(phase);
    ui.set_phase(phase);
  } else if ((phase == kPhaseDone || phase == kPhaseFailed) && selected > 0) {
    phase = kPhaseMain;
    state.phase.store(phase);
    ui.set_phase(phase);
  } else if ((phase == kPhaseDone || phase == kPhaseFailed || phase == kPhaseInjecting) && anyWorking == 0 && anyDone == 0 && anyFail == 0) {
    phase = kPhaseMain;
    state.phase.store(phase);
    ui.set_phase(phase);
  }

  bool anyUninjectFail = false;
  std::wstring failStage;
  for (const auto &mp : state.processes) {
    auto it = state.local.find(mp.pid);
    if (it != state.local.end() && it->second.finishedFail && mp.injected) {
      anyUninjectFail = true;
      failStage = it->second.stage;
      break;
    }
  }

  std::string status;
  if (anyUninjectFail) {
    if (failStage.find(L"event missing") != std::wstring::npos) {
      if (!embeddedDllHasUninjectHandler()) {
        status = "Uninject failed: embedded OVson.dll is the OLD one "
                 "(no uninject handler). The loader's .rc resource was "
                 "NOT refreshed during rebuild — delete OVsonLoader's "
                 "build folder and rebuild from scratch.";
      } else {
        status = "Uninject failed: embedded DLL has the handler, but "
                 "the running process didn't load it. Close ALL Minecraft "
                 "instances (Task Manager) and re-inject with this loader.";
      }
    } else if (failStage.find(L"access denied") != std::wstring::npos) {
      status = "Uninject failed: access denied to the uninject event. "
               "Run the loader with the same user as Minecraft.";
    } else {
      status = std::string("Uninject failed: ") + narrow(failStage);
    }
  } else switch (state.phase.load()) {
    case kPhaseDone:      status = "Injection complete";           break;
    case kPhaseFailed:    status = "Some instances failed to inject"; break;
    case kPhaseInjecting: status = "Injecting…";                   break;
    default:
      if (state.processes.empty()) {
        status = "Waiting for Minecraft to launch";
      } else {
        int sel = 0;
        for (const auto &mp : state.processes)
          if (!mp.injected && state.local[mp.pid].selected) sel++;
        if (sel == 0) status = "Select an instance to inject into";
        else if (sel == 1) status = "Ready to inject";
        else { char b[64]; snprintf(b, 64, "Ready to inject %d instances", sel); status = b; }
      }
      break;
  }
  ui.set_status_text(slint::SharedString(status));
}

LRESULT CALLBACK SubclassProc(HWND hWnd, UINT uMsg, WPARAM wParam,
                               LPARAM lParam, UINT_PTR, DWORD_PTR) {
  if (uMsg == WM_NCHITTEST) {
    LRESULT hit = DefSubclassProc(hWnd, uMsg, wParam, lParam);
    if (hit == HTCLIENT) {
      POINT pt = { GET_X_LPARAM(lParam), GET_Y_LPARAM(lParam) };
      ScreenToClient(hWnd, &pt);
      RECT rc;
      GetClientRect(hWnd, &rc);
      if (pt.y < 48 && pt.x < (rc.right - 48)) {
        return HTCAPTION;
      }
    }
    return hit;
  }
  if (uMsg == WM_MOUSEACTIVATE) {
    return MA_ACTIVATE;
  }
  return DefSubclassProc(hWnd, uMsg, wParam, lParam);
}

} // namespace

int APIENTRY wWinMain(HINSTANCE, HINSTANCE, LPWSTR, int) {
  HRSRC resSlint = FindResourceW(nullptr, MAKEINTRESOURCEW(2), RT_RCDATA);
  if (resSlint) {
    HGLOBAL hSlint = LoadResource(nullptr, resSlint);
    DWORD szSlint = SizeofResource(nullptr, resSlint);
    void* dataSlint = LockResource(hSlint);
    if (dataSlint && szSlint > 0) {
      wchar_t tempPath[MAX_PATH];
      GetTempPathW(MAX_PATH, tempPath);
      std::wstring dllPath = std::wstring(tempPath) + L"slint_cpp.dll";
      HANDLE hFile = CreateFileW(dllPath.c_str(), GENERIC_WRITE, 0, nullptr, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
      if (hFile != INVALID_HANDLE_VALUE) {
        DWORD written = 0;
        WriteFile(hFile, dataSlint, szSlint, &written, nullptr);
        CloseHandle(hFile);
      }
      LoadLibraryW(dllPath.c_str());
    }
  }


  auto &dll = embeddedDllBytes();
  bool payloadOk = !dll.empty();

  AppState state;
  state.model = std::make_shared<slint::VectorModel<PRow>>();
  auto ui = MainWindow::create();
  ui->set_processes(state.model);

  publishProcesses(*ui, state);
  std::thread([uiHandle = ui]() mutable {
    int lastPct = -1;
    Updater::State lastState = Updater::State::Idle;
    bool upToDateDismissScheduled = false;
    for (;;) {
      auto st = Updater::currentState();
      int pct = Updater::downloadPct();
      if (st != lastState || pct != lastPct) {
        lastState = st;
        lastPct = pct;
        std::string statusText;
        std::string versionText = "v" + Updater::info().remoteVersion;
        int stateCode = 1; // checking by default
        int progress = 0;
        bool legacyAvailable = false;
        switch (st) {
          case Updater::State::Idle:
            stateCode = 1; break;
          case Updater::State::Checking:
            stateCode = 1; break;
          case Updater::State::UpToDate:
            stateCode = 2; statusText = "Up to date";
            versionText = "v" + std::string(Updater::kBuildVersion);
            break;
          case Updater::State::UpdateAvailable:
            stateCode = 3; legacyAvailable = true;
            statusText = "Update available";
            break;
          case Updater::State::Downloading:
            stateCode = 4; legacyAvailable = true;
            progress = pct; statusText = "Downloading…";
            break;
          case Updater::State::Ready:
            stateCode = 5; legacyAvailable = true;
            progress = 100; statusText = "Ready";
            break;
          case Updater::State::Failed:
            stateCode = 6; statusText = Updater::lastError();
            if (statusText.empty()) statusText = "Update check failed";
            break;
        }
        slint::invoke_from_event_loop(
            [uiHandle, stateCode, statusText, versionText,
             legacyAvailable, progress]() {
              uiHandle->set_update_state(stateCode);
              uiHandle->set_update_available(legacyAvailable);
              uiHandle->set_update_version(slint::SharedString(versionText));
              uiHandle->set_update_status(slint::SharedString(statusText));
              uiHandle->set_update_progress(progress);
            });

        if (stateCode == 2 && !upToDateDismissScheduled) {
          upToDateDismissScheduled = true;
          std::thread([uiHandle]() mutable {
            std::this_thread::sleep_for(std::chrono::milliseconds(2200));
            slint::invoke_from_event_loop([uiHandle]() {
              uiHandle->set_update_state(0);
              uiHandle->set_update_available(false);
            });
          }).detach();
        }
      }
      std::this_thread::sleep_for(std::chrono::milliseconds(250));
    }
  }).detach();

  std::thread([uiHandle = ui, &state]() {
    auto sleep = [](int ms) {
      std::this_thread::sleep_for(std::chrono::milliseconds(ms));
    };
    sleep(800);  // hold the centered logo
    onUiThread([uiHandle, &state]() {
      state.phase.store(kPhaseSlide);
      uiHandle->set_phase(kPhaseSlide);
    });
    sleep(950);
    onUiThread([uiHandle, &state]() {
      state.phase.store(kPhaseMain);
      uiHandle->set_phase(kPhaseMain);
      uiHandle->set_update_state(1);
      uiHandle->set_update_available(true);
      Updater::startCheck();
    });
  }).detach();

  std::atomic<bool> stopScan{false};
  std::thread scanThread([uiHandle = ui, &state, &stopScan]() mutable {
    while (!stopScan.load()) {
      auto latest = findMinecraftProcesses();
      {
        std::lock_guard<std::mutex> lk(state.mtx);
        state.processes = std::move(latest);
        for (auto it = state.local.begin(); it != state.local.end();) {
          bool present = false;
          for (const auto &mp : state.processes)
            if (mp.pid == it->first) { present = true; break; }
          if (!present) it = state.local.erase(it);
          else ++it;
        }
      }
      onUiThread([uiHandle, &state]() mutable {
        publishProcesses(*uiHandle, state);
      });
      std::this_thread::sleep_for(std::chrono::milliseconds(500));
    }
  });

  ui->on_close_clicked([&]() { slint::quit_event_loop(); });

  ui->on_install_update([uiHandle = ui]() mutable {
    auto st = Updater::currentState();
    if (st == Updater::State::UpdateAvailable) {
      Updater::startDownload();
    } else if (st == Updater::State::Ready) {
      if (Updater::installAndRelaunch())
        slint::quit_event_loop();
    }
  });
  ui->on_toggle_row([&](int idx) {
    {
      std::lock_guard<std::mutex> lk(state.mtx);
      if (idx < 0 || idx >= (int)state.processes.size()) return;
      auto &mp = state.processes[idx];
      if (mp.injected) return;
      auto &lr = state.local[mp.pid];
      lr.selected = !lr.selected;
    }
    publishProcesses(*ui, state);
  });
  ui->on_uninject_row([&](int idx) {
    DWORD pid = 0;
    {
      std::lock_guard<std::mutex> lk(state.mtx);
      if (idx < 0 || idx >= (int)state.processes.size()) return;
      auto &mp = state.processes[idx];
      if (!mp.injected) return;
      pid = mp.pid;
      auto &lr = state.local[pid];
      lr.working = true;
      lr.finishedFail = false;
      lr.finishedOk = false;
      lr.stage = L"Uninjecting";
      lr.progress = 50;
    }
    publishProcesses(*ui, state);

    std::thread([uiHandle = ui, &state, pid]() {
      DWORD err = 0;
      bool ok = uninjectPid(pid, &err);
      {
        std::lock_guard<std::mutex> lk(state.mtx);
        auto &lr = state.local[pid];
        lr.selected = false;
        lr.finishedOk = false;
        lr.finishedFail = !ok;
        lr.working = false;
        lr.progress = ok ? 0 : 100;
        if (ok) {
          lr.stage.clear();
        } else {
          wchar_t buf[96];
          const wchar_t *kind =
              err == 2  ? L"event missing"
            : err == 5  ? L"access denied"
                        : L"err";
          wsprintfW(buf, L"Uninject failed (%s, %lu)", kind, err);
          lr.stage = buf;
        }
        if (ok) {
          for (auto &mp : state.processes) {
            if (mp.pid == pid) {
              mp.injected = false;
              break;
            }
          }
        }
      }
      onUiThread([uiHandle, &state]() mutable {
        publishProcesses(*uiHandle, state);
      });
    }).detach();
  });
  ui->on_inject_clicked([&]() {
    if (!payloadOk) return;
    std::vector<DWORD> targets;
    {
      std::lock_guard<std::mutex> lk(state.mtx);
      for (auto &kv : state.local) {
        kv.second.finishedFail = false;
        if (!kv.second.working) kv.second.stage.clear();
      }
      for (const auto &mp : state.processes) {
        auto &lr = state.local[mp.pid];
        if (lr.selected && !mp.injected) {
          targets.push_back(mp.pid);
          lr.working = true;
          lr.finishedOk = false;
          lr.finishedFail = false;
          lr.progress = 1;
          lr.stage = L"Starting";
        }
      }
      if (targets.empty()) return;
      state.phase.store(kPhaseInjecting);
    }
    ui->set_phase(kPhaseInjecting);
    publishProcesses(*ui, state);

    for (DWORD pid : targets) {
      std::thread([uiHandle = ui, &state, pid]() mutable {
        auto progress = [uiHandle, &state, pid](int pct,
                                                const std::wstring &stage) mutable {
          {
            std::lock_guard<std::mutex> lk(state.mtx);
            auto &lr = state.local[pid];
            lr.progress = pct;
            lr.stage = stage;
          }
          onUiThread([uiHandle, &state]() mutable {
            publishProcesses(*uiHandle, state);
          });
        };
        bool ok = injectPid(pid, progress);
        {
          std::lock_guard<std::mutex> lk(state.mtx);
          auto &lr = state.local[pid];
          lr.working = false;
          if (ok) {
            lr.finishedOk = true;
            lr.selected = false;
            for (auto &mp : state.processes) {
              if (mp.pid == pid) {
                mp.injected = true;
                break;
              }
            }
          }
          else    lr.finishedFail = true;
          lr.progress = 100;
        }
        onUiThread([uiHandle, &state]() mutable {
          publishProcesses(*uiHandle, state);
        });
      }).detach();
    }
  });

  if (!payloadOk) {
    state.phase.store(kPhaseFailed);
    ui->set_phase(kPhaseFailed);
    ui->set_status_text(slint::SharedString(
        "Payload missing — please reinstall the loader."));
  }

  ui->show();

  slint::invoke_from_event_loop([]() {
    HWND hwnd = FindWindowW(nullptr, L"OVson");
    if (!hwnd) hwnd = GetActiveWindow();
    if (!hwnd) hwnd = GetForegroundWindow();
    if (hwnd) {
      SetWindowSubclass(hwnd, SubclassProc, 1, 0);

      int screenWidth = GetSystemMetrics(SM_CXSCREEN);
      int screenHeight = GetSystemMetrics(SM_CYSCREEN);
      RECT rc;
      GetWindowRect(hwnd, &rc);
      int wWidth = rc.right - rc.left;
      int wHeight = rc.bottom - rc.top;
      int x = (screenWidth - wWidth) / 2;
      int y = (screenHeight - wHeight) / 2;
      SetWindowPos(hwnd, nullptr, x, y, 0, 0, SWP_NOZORDER | SWP_NOSIZE | SWP_NOACTIVATE);
    }
  });

  slint::run_event_loop();

  stopScan.store(true);
  if (scanThread.joinable()) scanThread.join();
  return 0;
}
