#include "injector.h"
#include <CommCtrl.h>
#pragma comment(lib, "Comctl32.lib")
#include "crash_dumps.h"
#include "log_tail.h"
#include "process_scan.h"
#include "settings.h"
#include "shutdown_coordinator.h"
#include "tray_icon.h"
#include "updater.h"
#include <commdlg.h>
#include <ShlObj.h>
#include "ovson_ui.h" // generated by slint_target_sources()
#include <slint.h>
#include <wininet.h>
#pragma comment(lib, "wininet.lib")

static ShutdownCoordinator g_shutdown;

std::string fetchUrl(const std::string& url) {
    HINTERNET hInt = InternetOpenA("OVsonLoader", INTERNET_OPEN_TYPE_PRECONFIG, NULL, NULL, 0);
    if (!hInt) return "";
    DWORD timeoutMs = 4000;
    InternetSetOptionA(hInt, INTERNET_OPTION_CONNECT_TIMEOUT, &timeoutMs,
                       sizeof(timeoutMs));
    InternetSetOptionA(hInt, INTERNET_OPTION_RECEIVE_TIMEOUT, &timeoutMs,
                       sizeof(timeoutMs));
    HINTERNET hConn = InternetOpenUrlA(hInt, url.c_str(), NULL, 0, INTERNET_FLAG_RELOAD, 0);
    if (!hConn) { InternetCloseHandle(hInt); return ""; }

    std::string result;
    char buffer[1024];
    DWORD read = 0;
    while (!g_shutdown.stopping() &&
           InternetReadFile(hConn, buffer, sizeof(buffer), &read) && read > 0) {
        result.append(buffer, read);
    }
    InternetCloseHandle(hConn);
    InternetCloseHandle(hInt);
    return result;
}

#include <sstream>
#include <Windows.h>
#include <TlHelp32.h>
#include <windowsx.h>
#include <shellapi.h>
#include <atomic>
#include <chrono>
#include <csignal>
#include <map>
#include <memory>
#include <mutex>
#include <set>
#include <string>
#include <thread>
#include <utility>
#include <vector>

class WorkerRegistry {
public:
  template <typename Fn> bool start(Fn &&fn) {
    if (g_shutdown.stopping()) return false;
    std::lock_guard<std::mutex> lock(m_mutex);
    if (g_shutdown.stopping()) return false;
    m_threads.emplace_back(std::forward<Fn>(fn));
    return true;
  }

  void joinAll() {
    std::vector<std::thread> threads;
    {
      std::lock_guard<std::mutex> lock(m_mutex);
      threads.swap(m_threads);
    }
    for (auto &thread : threads) {
      if (thread.joinable()) thread.join();
    }
  }

private:
  std::mutex m_mutex;
  std::vector<std::thread> m_threads;
};

static WorkerRegistry g_workers;

void loaderLog(const char* fmt, ...) {
    static std::mutex logMtx;
    std::lock_guard<std::mutex> lk(logMtx);

    char buf[2048];
    va_list args;
    va_start(args, fmt);
    vsnprintf(buf, sizeof(buf), fmt, args);
    va_end(args);

    SYSTEMTIME st;
    GetLocalTime(&st);
    char out[2560];
    int len = snprintf(out, sizeof(out), "[%02d:%02d:%02d.%03d] %s\n",
                       st.wHour, st.wMinute, st.wSecond, st.wMilliseconds, buf);

    OutputDebugStringA(out);

    wchar_t tempPath[MAX_PATH];
    if (GetTempPathW(MAX_PATH, tempPath)) {
        std::wstring logFile = std::wstring(tempPath) + L"OVsonLoader_debug.log";
        HANDLE h = CreateFileW(logFile.c_str(), FILE_APPEND_DATA, FILE_SHARE_READ, nullptr, OPEN_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
        if (h != INVALID_HANDLE_VALUE) {
            DWORD written = 0;
            WriteFile(h, out, len, &written, nullptr);
            FlushFileBuffers(h);
            CloseHandle(h);
        }
    }
    printf("%s", out);
    fflush(stdout);
}

static LONG WINAPI UnhandledCrashFilter(EXCEPTION_POINTERS* ep) {
    loaderLog("CRASH: Unhandled Exception Code: 0x%08X at Address: %p", 
              ep ? ep->ExceptionRecord->ExceptionCode : 0, 
              ep ? ep->ExceptionRecord->ExceptionAddress : nullptr);
    return EXCEPTION_EXECUTE_HANDLER;
}

namespace {

std::atomic<bool> g_minimizeToTray{true};

static HANDLE g_singleInstanceMutex = nullptr;
static HANDLE g_showWindowEvent = nullptr;
static HANDLE g_shutdownEvent = nullptr;
static std::atomic<bool> g_stopShowWatcher{false};
static std::thread g_showWatcherThread;

constexpr int kPhaseIntro     = 0;
constexpr int kPhaseSlide     = 1;
constexpr int kPhaseMain      = 2;
constexpr int kPhaseInjecting = 3;
constexpr int kPhaseDone      = 4;
constexpr int kPhaseFailed    = 5;

struct LocalRow {
  bool selected = false;
  int  progress = 0;
  std::wstring stage;
  bool working = false;
  bool finishedOk = false;
  bool finishedFail = false;
};

std::wstring widen(const std::string &s) {
  if (s.empty()) return {};
  int n = MultiByteToWideChar(CP_UTF8, 0, s.data(), (int)s.size(), nullptr, 0);
  std::wstring w(n, L'\0');
  MultiByteToWideChar(CP_UTF8, 0, s.data(), (int)s.size(), w.data(), n);
  return w;
}
std::string narrow(const std::wstring &w) {
  if (w.empty()) return {};
  int n = WideCharToMultiByte(CP_UTF8, 0, w.data(), (int)w.size(),
                              nullptr, 0, nullptr, nullptr);
  std::string s(n, '\0');
  WideCharToMultiByte(CP_UTF8, 0, w.data(), (int)w.size(),
                      s.data(), n, nullptr, nullptr);
  return s;
}

static HWND getSlintHwnd() {
  struct EnumData {
    DWORD pid;
    HWND hwnd;
  };
  EnumData data = { GetCurrentProcessId(), nullptr };
  EnumWindows([](HWND hwnd, LPARAM lParam) -> BOOL {
    EnumData *d = (EnumData*)lParam;
    DWORD pid = 0;
    GetWindowThreadProcessId(hwnd, &pid);
    if (pid == d->pid) {
      wchar_t title[128];
      GetWindowTextW(hwnd, title, 128);
      if (wcscmp(title, L"OVson") == 0) {
        d->hwnd = hwnd;
        return FALSE;
      }
    }
    return TRUE;
  }, (LPARAM)&data);

  if (data.hwnd) return data.hwnd;
  HWND hwnd = FindWindowW(nullptr, L"OVson");
  if (!hwnd) hwnd = GetActiveWindow();
  if (!hwnd) hwnd = GetForegroundWindow();
  return hwnd;
}

struct AppState {
  std::mutex                                mtx;
  std::map<DWORD, LocalRow>                 local;
  std::vector<MinecraftProcess>             processes;
  std::atomic<int>                          phase{kPhaseIntro};
  std::shared_ptr<slint::VectorModel<PRow>> model;
  std::set<DWORD>                           autoInjectAttempted;
  std::atomic<bool>                         autoInjectEnabled{false};
  ULONGLONG                                 startTime{GetTickCount64()};
};

template <class F> void onUiThread(F &&f) {
  if (g_shutdown.stopping()) return;
  slint::invoke_from_event_loop(
      [callback = std::forward<F>(f)]() mutable {
        if (!g_shutdown.stopping()) callback();
      });
}

bool waitForShutdown(DWORD milliseconds) {
  return g_shutdownEvent &&
         WaitForSingleObject(g_shutdownEvent, milliseconds) == WAIT_OBJECT_0;
}

void requestLoaderShutdown(HWND hwnd, const char *source) {
  const bool firstRequest = g_shutdown.request();
  loaderLog("Shutdown request source=%s first=%d stage=%s",
            source ? source : "unknown", firstRequest ? 1 : 0,
            shutdownStageName(g_shutdown.stage()));
  if (!firstRequest) return;

  g_stopShowWatcher.store(true, std::memory_order_release);
  requestInjectorShutdown();
  if (g_shutdownEvent) SetEvent(g_shutdownEvent);
  if (g_showWindowEvent) SetEvent(g_showWindowEvent);
  Tray::beginShutdown();
  if (hwnd && IsWindow(hwnd)) ShowWindow(hwnd, SW_HIDE);
  slint::quit_event_loop();
}

void publishProcesses(const MainWindow &ui, AppState &state) {
  std::lock_guard<std::mutex> lk(state.mtx);

  int anyWorking = 0;
  int anyDone = 0;
  int anyFail = 0;
  int selected = 0;
  std::vector<PRow> targetRows;
  for (const auto &mp : state.processes) {
    LocalRow &lr = state.local[mp.pid];
    if (mp.injected) {
      lr.selected = false;
      if (!lr.finishedFail) lr.finishedOk = true;
    } else {
      lr.finishedOk = false;
    }
    PRow r;
    r.pid = (int)mp.pid;
    r.title = slint::SharedString(narrow(mp.windowTitle));
    r.selected = lr.selected && !mp.injected;
    r.injected = mp.injected;
    r.progress = lr.progress;
    r.stage = slint::SharedString(narrow(lr.stage));
    r.working = lr.working;
    r.finished_ok = lr.finishedOk;
    r.finished_fail = lr.finishedFail;

    r.launcher_label = slint::SharedString(launcherLabel(mp.launcher));
    {
      uint32_t argb = launcherColor(mp.launcher);
      uint8_t a = (argb >> 24) & 0xFF;
      uint8_t cr = (argb >> 16) & 0xFF;
      uint8_t cg = (argb >> 8) & 0xFF;
      uint8_t cb = argb & 0xFF;
      r.launcher_color = slint::Color::from_argb_uint8(a, cr, cg, cb);
    }
    r.mc_version = slint::SharedString(narrow(mp.mcVersion));

    if (mp.privateMemBytes >= (1ULL << 30)) {
      char buf[24];
      double gb = (double)mp.privateMemBytes / (1ULL << 30);
      snprintf(buf, sizeof(buf), "%.1f GB", gb);
      r.memory_text = slint::SharedString(buf);
    } else if (mp.privateMemBytes >= (1ULL << 20)) {
      char buf[24];
      uint64_t mb = mp.privateMemBytes / (1ULL << 20);
      snprintf(buf, sizeof(buf), "%llu MB", (unsigned long long)mb);
      r.memory_text = slint::SharedString(buf);
    } else {
      r.memory_text = slint::SharedString("");
    }

    if (mp.uptimeSeconds >= 60) {
      char buf[24];
      uint32_t mins  = mp.uptimeSeconds / 60;
      uint32_t hours = mins / 60;
      mins %= 60;
      if (hours > 0)  snprintf(buf, sizeof(buf), "%uh %um", hours, mins);
      else            snprintf(buf, sizeof(buf), "%um", mins);
      r.uptime_text = slint::SharedString(buf);
    } else {
      r.uptime_text = slint::SharedString("");
    }

    targetRows.push_back(r);
    if (lr.working) anyWorking++;
    if (lr.finishedOk) anyDone++;
    if (lr.finishedFail) anyFail++;
    if (r.selected) selected++;
  }

  if (state.model) {
    size_t currentCount = state.model->row_count();
    size_t targetCount = targetRows.size();
    if (currentCount != targetCount) {
      state.model->clear();
      for (const auto &r : targetRows) {
        state.model->push_back(r);
      }
    } else {
      for (size_t i = 0; i < targetCount; ++i) {
        auto optRow = state.model->row_data(i);
        if (optRow) {
          const PRow &existing = *optRow;
          const PRow &target = targetRows[i];
          if (existing.pid != target.pid ||
              existing.title != target.title ||
              existing.selected != target.selected ||
              existing.injected != target.injected ||
              existing.progress != target.progress ||
              existing.stage != target.stage ||
              existing.working != target.working ||
              existing.finished_ok != target.finished_ok ||
              existing.finished_fail != target.finished_fail ||
              existing.launcher_label != target.launcher_label ||
              existing.mc_version != target.mc_version ||
              existing.memory_text != target.memory_text ||
              existing.uptime_text != target.uptime_text) {
            state.model->set_row_data(i, target);
          }
        }
      }
    }
  }

  ui.set_selected_count(selected);

  int phase = state.phase.load();
  if (phase == kPhaseInjecting && anyWorking == 0) {
    if (anyFail > 0 && anyDone == 0)      phase = kPhaseFailed;
    else if (anyFail > 0)                 phase = kPhaseFailed;
    else                                  phase = kPhaseDone;
    state.phase.store(phase);
    ui.set_phase(phase);
  } else if ((phase == kPhaseDone || phase == kPhaseFailed) && selected > 0) {
    phase = kPhaseMain;
    state.phase.store(phase);
    ui.set_phase(phase);
  } else if ((phase == kPhaseDone || phase == kPhaseFailed || phase == kPhaseInjecting) && anyWorking == 0 && anyDone == 0 && anyFail == 0) {
    phase = kPhaseMain;
    state.phase.store(phase);
    ui.set_phase(phase);
  }

  bool anyUninjectFail = false;
  std::wstring failStage;
  for (const auto &mp : state.processes) {
    auto it = state.local.find(mp.pid);
    if (it != state.local.end() && it->second.finishedFail && mp.injected) {
      anyUninjectFail = true;
      failStage = it->second.stage;
      break;
    }
  }

  std::string status;
  if (anyUninjectFail) {
    if (failStage.find(L"event missing") != std::wstring::npos) {
      if (!embeddedDllHasUninjectHandler()) {
        status = "Uninject failed: embedded OVson.dll is the OLD one "
                 "(no uninject handler). The loader's .rc resource was "
                 "NOT refreshed during rebuild — delete OVsonLoader's "
                 "build folder and rebuild from scratch.";
      } else {
        status = "Uninject failed: embedded DLL has the handler, but "
                 "the running process didn't load it. Close ALL Minecraft "
                 "instances (Task Manager) and re-inject with this loader.";
      }
    } else if (failStage.find(L"access denied") != std::wstring::npos) {
      status = "Uninject failed: access denied to the uninject event. "
               "Run the loader with the same user as Minecraft.";
    } else {
      status = std::string("Uninject failed: ") + narrow(failStage);
    }
  } else switch (state.phase.load()) {
    case kPhaseDone:      status = "Injection complete";           break;
    case kPhaseFailed:    status = "Some instances failed to inject"; break;
    case kPhaseInjecting: status = "Injecting…";                   break;
    default:
      if (state.processes.empty()) {
        status = "Waiting for Minecraft to launch";
      } else {
        int sel = 0;
        for (const auto &mp : state.processes)
          if (!mp.injected && state.local[mp.pid].selected) sel++;
        if (sel == 0) status = "Select an instance to inject into";
        else if (sel == 1) status = "Ready to inject";
        else { char b[64]; snprintf(b, 64, "Ready to inject %d instances", sel); status = b; }
      }
      break;
  }
  ui.set_status_text(slint::SharedString(status));
}

LRESULT CALLBACK SubclassProc(HWND hWnd, UINT uMsg, WPARAM wParam,
                               LPARAM lParam, UINT_PTR uIdSubclass, DWORD_PTR dwRefData) {
  if (uMsg == WM_CLOSE) {
    loaderLog("SubclassProc: WM_CLOSE received for hwnd=%p", hWnd);
  } else if (uMsg == WM_DESTROY) {
    loaderLog("SubclassProc: WM_DESTROY received for hwnd=%p", hWnd);
  } else if (uMsg == WM_SYSCOMMAND && (wParam & 0xFFF0) == SC_CLOSE) {
    loaderLog("SubclassProc: WM_SYSCOMMAND SC_CLOSE received for hwnd=%p", hWnd);
  }

  if (uMsg == WM_NCHITTEST) {
    LRESULT hit = DefSubclassProc(hWnd, uMsg, wParam, lParam);
    if (hit == HTCLIENT) {
      POINT pt = { GET_X_LPARAM(lParam), GET_Y_LPARAM(lParam) };
      ScreenToClient(hWnd, &pt);
      RECT rc;
      GetClientRect(hWnd, &rc);
      
      HDC hdc = GetDC(hWnd);
      int dpi = GetDeviceCaps(hdc, LOGPIXELSX);
      ReleaseDC(hWnd, hdc);
      
      int hitY = MulDiv(48, dpi, 96);
      int hitX = rc.right - MulDiv(76, dpi, 96);
      
      int navHoleW = MulDiv(440, dpi, 96);
      int navStart = (rc.right - navHoleW) / 2;
      int navEnd   = navStart + navHoleW;
      
      bool inNavHole = (pt.x >= navStart && pt.x <= navEnd);
      if (pt.y < hitY && pt.x < hitX && !inNavHole) {
        return HTCAPTION;
      }
    }
    return hit;
  }
  if (uMsg == WM_MOUSEACTIVATE) {
    return MA_ACTIVATE;
  }
  return DefSubclassProc(hWnd, uMsg, wParam, lParam);
}

} // namespace

static LONG WINAPI sehLogFilter(EXCEPTION_POINTERS* ep) {
  if (ep && ep->ExceptionRecord) {
    DWORD code = ep->ExceptionRecord->ExceptionCode;
    if (code == 0xC0000005 || code == 0xC0000374 || code == 0xC00000FD ||
        code == 0xC0000409) {
      wchar_t ad[MAX_PATH];
      if (SUCCEEDED(SHGetFolderPathW(nullptr, CSIDL_LOCAL_APPDATA, nullptr,
                                      SHGFP_TYPE_CURRENT, ad))) {
        wchar_t lp[MAX_PATH];
        wsprintfW(lp, L"%s\\OVson\\OVsonLoader_SEH.log", ad);
        FILE* f = nullptr;
        _wfopen_s(&f, lp, L"a");
        if (f) {
          SYSTEMTIME st; GetLocalTime(&st);
          fprintf(f, "[%02d:%02d:%02d.%03d] SEH Code=0x%08X Addr=%p\n",
                  st.wHour, st.wMinute, st.wSecond, st.wMilliseconds,
                  code, ep->ExceptionRecord->ExceptionAddress);
          fflush(f); fclose(f);
        }
      }
    }
  }
  return EXCEPTION_CONTINUE_SEARCH;
}

int APIENTRY wWinMain(HINSTANCE, HINSTANCE, LPWSTR, int) {
  _putenv("SLINT_BACKEND=winit-software");
  {
    wchar_t ad[MAX_PATH];
    if (SUCCEEDED(SHGetFolderPathW(nullptr, CSIDL_LOCAL_APPDATA, nullptr,
                                    SHGFP_TYPE_CURRENT, ad))) {
      std::wstring dir = std::wstring(ad) + L"\\OVson";
      CreateDirectoryW(dir.c_str(), nullptr);
      std::wstring lp = dir + L"\\OVsonLoader_Crash.log";
      FILE *d1 = nullptr, *d2 = nullptr;
      _wfreopen_s(&d1, lp.c_str(), L"a", stdout);
      _wfreopen_s(&d2, lp.c_str(), L"a", stderr);
      if (d1) setvbuf(d1, nullptr, _IONBF, 0);
      if (d2) setvbuf(d2, nullptr, _IONBF, 0);
      setvbuf(stdout, nullptr, _IONBF, 0);
      setvbuf(stderr, nullptr, _IONBF, 0);
    }
  }

  SetUnhandledExceptionFilter(UnhandledCrashFilter);
  AddVectoredExceptionHandler(1, sehLogFilter);
  loaderLog("=== OVsonLoader started (PID: %lu) ===", GetCurrentProcessId());

  g_showWindowEvent = CreateEventW(nullptr, FALSE, FALSE, L"Local\\OVsonLoaderShowEvent");
  g_shutdownEvent = CreateEventW(nullptr, TRUE, FALSE, nullptr);
  g_singleInstanceMutex = CreateMutexW(nullptr, FALSE, L"Local\\OVsonLoaderSingleInstance");
  if (g_singleInstanceMutex && GetLastError() == ERROR_ALREADY_EXISTS) {
    loaderLog("Another instance detected. Signaling show event and exiting.");
    if (g_showWindowEvent) {
      SetEvent(g_showWindowEvent);
      Sleep(200);
      CloseHandle(g_showWindowEvent);
      g_showWindowEvent = nullptr;
    }
    if (g_shutdownEvent) {
      CloseHandle(g_shutdownEvent);
      g_shutdownEvent = nullptr;
    }
    CloseHandle(g_singleInstanceMutex);
    return 0;
  }

  auto &dll = embeddedDllBytes();
  bool payloadOk = !dll.empty();

  AppState state;
  state.model = std::make_shared<slint::VectorModel<PRow>>();
  loaderLog("Creating MainWindow...");
  auto ui = MainWindow::create();
  loaderLog("MainWindow created successfully.");
  ui->set_processes(state.model);

  ui->on_open_link([](slint::SharedString link) {
    ShellExecuteA(nullptr, "open", link.data(), nullptr, nullptr, SW_SHOWNORMAL);
  });

  g_workers.start([ui = ui]() {
    std::string md = fetchUrl("https://gist.githubusercontent.com/alperenproo/125c7a70728a16fdad215ca57adc0edc/raw");
    
    struct TempBlock {
        std::string type;
        std::string content;
        std::string url;
        std::string localImgPath;
    };
    std::vector<TempBlock> temp;

    if (!md.empty()) {
        std::istringstream iss(md);
        std::string line;
        while (std::getline(iss, line)) {
            if (!line.empty() && line.back() == '\r') line.pop_back();
            if (line.empty()) continue;

            if (line.size() >= 2 && line.substr(0, 2) == "# ") {
                temp.push_back({"h1", line.substr(2), "", ""});
                continue;
            }
            if (line.size() >= 3 && line.substr(0, 3) == "## ") {
                temp.push_back({"h2", line.substr(3), "", ""});
                continue;
            }

            std::string cleanText;
            std::vector<TempBlock> extracted;

            size_t i = 0;
            while (i < line.size()) {
                if (line[i] == '!' && i + 1 < line.size() && line[i+1] == '[') {
                    size_t endBracket = line.find(']', i + 2);
                    if (endBracket != std::string::npos && endBracket + 1 < line.size() && line[endBracket+1] == '(') {
                        size_t endParen = line.find(')', endBracket + 2);
                        if (endParen != std::string::npos) {
                            std::string alt = line.substr(i + 2, endBracket - (i + 2));
                            std::string url = line.substr(endBracket + 2, endParen - (endBracket + 2));
                            extracted.push_back({"image", alt, url, ""});
                            i = endParen + 1;
                            continue;
                        }
                    }
                }
                else if (line[i] == '[') {
                    size_t endBracket = line.find(']', i + 1);
                    if (endBracket != std::string::npos && endBracket + 1 < line.size() && line[endBracket+1] == '(') {
                        size_t endParen = line.find(')', endBracket + 2);
                        if (endParen != std::string::npos) {
                            std::string text = line.substr(i + 1, endBracket - (i + 1));
                            std::string url = line.substr(endBracket + 2, endParen - (endBracket + 2));
                            extracted.push_back({"link", text, url, ""});
                            i = endParen + 1;
                            continue;
                        }
                    }
                }
                
                cleanText += line[i];
                i++;
            }

            if (!cleanText.empty()) {
                temp.push_back({"text", cleanText, "", ""});
            }
            for (auto& ext : extracted) {
                if (ext.type == "image") {
                    std::string imgData = fetchUrl(ext.url);
                    if (!imgData.empty()) {
                        char tmpPath[MAX_PATH];
                        GetTempPathA(MAX_PATH, tmpPath);
                        char tmpFile[MAX_PATH];
                        GetTempFileNameA(tmpPath, "ovs", 0, tmpFile);
                        
                        FILE* f = nullptr;
                        fopen_s(&f, tmpFile, "wb");
                        if (f) {
                            fwrite(imgData.data(), 1, imgData.size(), f);
                            fclose(f);
                            ext.localImgPath = tmpFile;
                        }
                    }
                }
                temp.push_back(ext);
            }
        }
    }

    onUiThread([ui, temp]() {
        auto model = std::make_shared<slint::VectorModel<MarkdownBlock>>();
        for (const auto& t : temp) {
            MarkdownBlock b;
            b.block_type = slint::SharedString(t.type.c_str());
            b.content = slint::SharedString(t.content.c_str());
            b.url = slint::SharedString(t.url.c_str());
            if (t.type == "image" && !t.localImgPath.empty()) {
                b.img = slint::Image::load_from_path(slint::SharedString(t.localImgPath.c_str()));
            }
            model->push_back(b);
        }
        ui->set_announcements(model);
    });
  });

  Settings::Values prefs = Settings::load();
  ui->set_setting_auto_inject(prefs.autoInject);
  ui->set_setting_start_with_windows(prefs.startWithWindows);
  ui->set_setting_minimize_to_tray(prefs.minimizeToTray);
  ui->set_setting_auto_check_updates(prefs.autoCheckUpdates);
  ui->set_setting_dll_slot(prefs.dllSlot);
  ui->set_setting_custom_dll_path(
      slint::SharedString(narrow(prefs.customDllPath)));
  ui->set_setting_lunar_log_path(
      slint::SharedString(narrow(prefs.lunarLogPath)));
  ui->set_setting_badlion_log_path(
      slint::SharedString(narrow(prefs.badlionLogPath)));
  ui->set_setting_legacy_badlion_log_path(
      slint::SharedString(narrow(prefs.legacyBadlionLogPath)));
  setActiveSlot(prefs.dllSlot, prefs.customDllPath);
  state.autoInjectEnabled.store(prefs.autoInject);
  g_minimizeToTray.store(prefs.minimizeToTray);

  auto logModelPtr = std::make_shared<std::shared_ptr<slint::VectorModel<LogLine>>>(
      std::make_shared<slint::VectorModel<LogLine>>());
  ui->set_log_lines(*logModelPtr);

  static LogTail s_tail;

  ui->on_open_log_folder([]() {
    wchar_t appData[MAX_PATH] = L"";
    if (SUCCEEDED(SHGetFolderPathW(nullptr, CSIDL_LOCAL_APPDATA,
                                    nullptr, SHGFP_TYPE_CURRENT,
                                    appData))) {
      std::wstring dir = std::wstring(appData) + L"\\OVson\\logs";
      CreateDirectoryW(dir.c_str(), nullptr);
      ShellExecuteW(nullptr, L"open", dir.c_str(), nullptr, nullptr,
                    SW_SHOWNORMAL);
    }
  });
  ui->on_clear_log([logModelPtr, uiHandle = ui]() {
    *logModelPtr = std::make_shared<slint::VectorModel<LogLine>>();
    uiHandle->set_log_lines(*logModelPtr);
    uiHandle->set_log_path(slint::SharedString(""));
  });

  {
    auto dumps = CrashDumps::scan();
    ui->set_dump_count((int)dumps.size());
  }
  ui->on_open_dumps_folder([]() {
    CrashDumps::openInExplorer(L"");
  });
  ui->on_dismiss_crash_dumps([uiHandle = ui]() {
    uiHandle->set_dump_count(0);
  });
  ui->on_report_modal_yes([]() {
    CrashDumps::openInExplorer(L"");
    ShellExecuteW(nullptr, L"open",
                  L"https://github.com/alperenproo/ovson/issues/new"
                  L"?labels=crash&template=crash.md",
                  nullptr, nullptr, SW_SHOWNORMAL);
  });
  ui->on_report_modal_no([uiHandle = ui]() {
    int n = CrashDumps::deleteAll();
    uiHandle->set_dump_count(0);
    char msg[96];
    sprintf_s(msg, "Removed %d dump file%s.", n, n == 1 ? "" : "s");
    uiHandle->set_status_text(slint::SharedString(msg));
  });

  ui->on_settings_changed([uiHandle = ui, &state]() {
    Settings::Values v;
    v.autoInject       = uiHandle->get_setting_auto_inject();
    v.startWithWindows = uiHandle->get_setting_start_with_windows();
    v.minimizeToTray   = uiHandle->get_setting_minimize_to_tray();
    v.autoCheckUpdates = uiHandle->get_setting_auto_check_updates();
    v.dllSlot          = uiHandle->get_setting_dll_slot();
    v.customDllPath    = widen(std::string(
        uiHandle->get_setting_custom_dll_path().data()));
    v.lunarLogPath     = widen(std::string(
        uiHandle->get_setting_lunar_log_path().data()));
    v.badlionLogPath   = widen(std::string(
        uiHandle->get_setting_badlion_log_path().data()));
    v.legacyBadlionLogPath = widen(std::string(
        uiHandle->get_setting_legacy_badlion_log_path().data()));
    Settings::save(v);
    setActiveSlot(v.dllSlot, v.customDllPath);
    state.autoInjectEnabled.store(v.autoInject);
    g_minimizeToTray.store(v.minimizeToTray);

    if (v.autoCheckUpdates) {
      if (uiHandle->get_update_state() == 0) {
        uiHandle->set_update_state(1);
        uiHandle->set_update_available(true);
        Updater::startCheck();
      }
    } else {
      uiHandle->set_update_state(0);
      uiHandle->set_update_available(false);
    }
  });

  auto pickLogFile = [](const wchar_t *title) -> std::wstring {
    wchar_t file[MAX_PATH] = L"";
    OPENFILENAMEW ofn{};
    ofn.lStructSize = sizeof(ofn);
    ofn.lpstrFilter = L"Log Files (*.log)\0*.log\0All files (*.*)\0*.*\0";
    ofn.lpstrFile = file;
    ofn.nMaxFile = MAX_PATH;
    ofn.lpstrTitle = title;
    ofn.Flags = OFN_FILEMUSTEXIST | OFN_HIDEREADONLY | OFN_PATHMUSTEXIST | OFN_NOCHANGEDIR;
    if (GetOpenFileNameW(&ofn) && file[0] != L'\0') {
      return file;
    }
    return L"";
  };

  ui->on_pick_lunar_log_path([uiHandle = ui, pickLogFile]() {
    std::wstring chosen = pickLogFile(L"Select Lunar Client Log File");
    if (!chosen.empty()) {
      uiHandle->set_setting_lunar_log_path(slint::SharedString(narrow(chosen)));
      uiHandle->invoke_settings_changed();
    }
  });

  ui->on_pick_badlion_log_path([uiHandle = ui, pickLogFile]() {
    std::wstring chosen = pickLogFile(L"Select Badlion Client Log File");
    if (!chosen.empty()) {
      uiHandle->set_setting_badlion_log_path(slint::SharedString(narrow(chosen)));
      uiHandle->invoke_settings_changed();
    }
  });

  ui->on_pick_legacy_badlion_log_path([uiHandle = ui, pickLogFile]() {
    std::wstring chosen = pickLogFile(L"Select Legacy Badlion / Vanilla Log File");
    if (!chosen.empty()) {
      uiHandle->set_setting_legacy_badlion_log_path(slint::SharedString(narrow(chosen)));
      uiHandle->invoke_settings_changed();
    }
  });

  ui->on_pick_custom_dll([uiHandle = ui]() {
    wchar_t file[MAX_PATH] = L"";
    OPENFILENAMEW ofn{};
    ofn.lStructSize  = sizeof(ofn);
    ofn.lpstrFilter  = L"OVson DLL (*.dll)\0*.dll\0All files\0*.*\0";
    ofn.lpstrFile    = file;
    ofn.nMaxFile     = MAX_PATH;
    ofn.lpstrTitle   = L"Select custom OVson.dll";
    ofn.Flags        = OFN_FILEMUSTEXIST | OFN_HIDEREADONLY
                       | OFN_PATHMUSTEXIST | OFN_NOCHANGEDIR;
    if (GetOpenFileNameW(&ofn) && file[0] != L'\0') {
      uiHandle->set_setting_custom_dll_path(
          slint::SharedString(narrow(file)));
      uiHandle->invoke_settings_changed();
    }
  });

  publishProcesses(*ui, state);
  g_workers.start([uiHandle = ui]() mutable {
    int lastPct = -1;
    Updater::State lastState = Updater::State::Idle;
    bool upToDateDismissScheduled = false;
    bool failedDismissScheduled = false;
    while (!g_shutdown.stopping()) {
      auto st = Updater::currentState();
      int pct = Updater::downloadPct();
      if (st != lastState || pct != lastPct) {
        lastState = st;
        lastPct = pct;
        std::string statusText;
        std::string versionText = "v" + Updater::info().remoteVersion;
        int stateCode = 1; // checking by default
        int progress = 0;
        bool legacyAvailable = false;
        switch (st) {
          case Updater::State::Idle:
            stateCode = 1; break;
          case Updater::State::Checking:
            stateCode = 1; break;
          case Updater::State::UpToDate:
            stateCode = 2; statusText = "Up to date";
            versionText = "v" + std::string(Updater::kBuildVersion);
            break;
          case Updater::State::UpdateAvailable:
            stateCode = 3; legacyAvailable = true;
            statusText = "Update available";
            break;
          case Updater::State::Downloading:
            stateCode = 4; legacyAvailable = true;
            progress = pct; statusText = "Downloading…";
            break;
          case Updater::State::Ready:
            stateCode = 5; legacyAvailable = true;
            progress = 100; statusText = "Ready";
            break;
          case Updater::State::Failed:
            stateCode = 6; statusText = Updater::lastError();
            if (statusText.empty()) statusText = "Update check failed";
            break;
        }
        onUiThread(
            [uiHandle, stateCode, statusText, versionText,
             legacyAvailable, progress]() {
              uiHandle->set_update_state(stateCode);
              uiHandle->set_update_available(legacyAvailable);
              uiHandle->set_update_version(slint::SharedString(versionText));
              uiHandle->set_update_status(slint::SharedString(statusText));
              uiHandle->set_update_progress(progress);
            });

        if (stateCode == 2 && !upToDateDismissScheduled) {
          upToDateDismissScheduled = true;
          g_workers.start([uiHandle]() mutable {
            if (waitForShutdown(2200)) return;
            onUiThread([uiHandle]() {
              uiHandle->set_update_state(0);
              uiHandle->set_update_available(false);
            });
          });
        }
        if (stateCode != 6) failedDismissScheduled = false;
        if (stateCode == 6 && !failedDismissScheduled) {
          failedDismissScheduled = true;
          g_workers.start([uiHandle]() mutable {
            if (waitForShutdown(6000)) return;
            onUiThread([uiHandle]() {
              if (uiHandle->get_update_state() == 6) {
                uiHandle->set_update_state(0);
                uiHandle->set_update_available(false);
              }
            });
          });
        }
      }
      if (waitForShutdown(250)) break;
    }
  });

  g_workers.start([uiHandle = ui, &state]() {
    if (waitForShutdown(800)) return;  // hold the centered logo
    onUiThread([uiHandle, &state]() {
      state.phase.store(kPhaseSlide);
      uiHandle->set_phase(kPhaseSlide);
    });
    if (waitForShutdown(950)) return;
    onUiThread([uiHandle, &state]() {
      state.phase.store(kPhaseMain);
      uiHandle->set_phase(kPhaseMain);
      if (uiHandle->get_setting_auto_check_updates()) {
        uiHandle->set_update_state(1);
        uiHandle->set_update_available(true);
        Updater::startCheck();
      } else {
        uiHandle->set_update_state(0);
        uiHandle->set_update_available(false);
      }
    });
  });

  std::atomic<bool> stopScan{false};
  std::thread scanThread([uiHandle = ui, &state, &stopScan]() mutable {
    while (!stopScan.load() && !g_shutdown.stopping()) {
      auto latest = findMinecraftProcesses();
      bool shouldAutoInject = false;
      {
        std::lock_guard<std::mutex> lk(state.mtx);
        state.processes = std::move(latest);
        for (auto it = state.local.begin(); it != state.local.end();) {
          bool present = false;
          for (const auto &mp : state.processes)
            if (mp.pid == it->first) { present = true; break; }
          if (!present) it = state.local.erase(it);
          else ++it;
        }
        for (auto it = state.autoInjectAttempted.begin();
             it != state.autoInjectAttempted.end();) {
          bool present = false;
          for (const auto &mp : state.processes)
            if (mp.pid == *it) { present = true; break; }
          if (!present) it = state.autoInjectAttempted.erase(it);
          else ++it;
        }
        ULONGLONG uptimeMs = GetTickCount64() - state.startTime;
        if (state.phase.load() == kPhaseMain &&
            state.autoInjectEnabled.load() &&
            uptimeMs >= 3500) {
          for (const auto &mp : state.processes) {
            if (mp.injected) {
              state.autoInjectAttempted.insert(mp.pid);
              continue;
            }
            if (state.autoInjectAttempted.count(mp.pid)) continue;
            auto &lr = state.local[mp.pid];
            if (lr.working) continue;
            lr.selected = true;
            state.autoInjectAttempted.insert(mp.pid);
            shouldAutoInject = true;
          }
        }
      }
      if (stopScan.load() || g_shutdown.stopping()) break;
      onUiThread([uiHandle, &state, shouldAutoInject]() mutable {
        publishProcesses(*uiHandle, state);
        if (shouldAutoInject) {
          uiHandle->invoke_inject_clicked();
        }
      });
      if (waitForShutdown(500)) break;
    }
  });

  static std::atomic<bool> s_trayBalloonShown{false};
  ui->on_close_clicked([uiHandle = ui]() mutable {
    bool minToTray = uiHandle->get_setting_minimize_to_tray();
    loaderLog("on_close_clicked triggered (minimizeToTray=%d)", minToTray);
    if (!minToTray) {
      requestLoaderShutdown(getSlintHwnd(), "window-close");
      return;
    }
    HWND hwnd = getSlintHwnd();
    if (hwnd) ShowWindow(hwnd, SW_HIDE);
    if (!s_trayBalloonShown.exchange(true)) {
      Tray::notify(L"OVson",
                   L"Running in the system tray. "
                   L"Right-click the icon to quit.");
    }
  });

  ui->on_minimize_clicked([uiHandle = ui]() mutable {
    HWND hwnd = getSlintHwnd();
    if (hwnd) {
      LONG style = GetWindowLongW(hwnd, GWL_STYLE);
      if (!(style & WS_MINIMIZEBOX)) {
        SetWindowLongW(hwnd, GWL_STYLE, style | WS_MINIMIZEBOX | WS_SYSMENU);
      }
      ShowWindow(hwnd, SW_MINIMIZE);
    }
  });

  ui->set_build_version(slint::SharedString(Updater::kBuildVersion));
  ui->on_open_github([]() {
    ShellExecuteW(nullptr, L"open",
                  L"https://github.com/alperenproo/ovson", nullptr,
                  nullptr, SW_SHOWNORMAL);
  });
  ui->on_view_changelog([]() {
    ShellExecuteW(nullptr, L"open",
                  L"https://github.com/alperenproo/ovson/releases/latest",
                  nullptr, nullptr, SW_SHOWNORMAL);
  });

  ui->on_install_update([uiHandle = ui]() mutable {
    auto st = Updater::currentState();
    if (st == Updater::State::UpdateAvailable) {
      Updater::startDownload();
    } else if (st == Updater::State::Ready) {
      if (Updater::installAndRelaunch())
        requestLoaderShutdown(getSlintHwnd(), "update-install");
    }
  });
  ui->on_toggle_row([&](int idx) {
    {
      std::lock_guard<std::mutex> lk(state.mtx);
      if (idx < 0 || idx >= (int)state.processes.size()) return;
      auto &mp = state.processes[idx];
      if (mp.injected) return;
      auto &lr = state.local[mp.pid];
      lr.selected = !lr.selected;
    }
    publishProcesses(*ui, state);
  });
  ui->on_show_context_menu([&state, uiHandle = ui](int idx) {
    DWORD pid = 0;
    bool injected = false;
    bool selected = false;
    std::wstring exePath;
    {
      std::lock_guard<std::mutex> lk(state.mtx);
      if (idx < 0 || idx >= (int)state.processes.size()) return;
      const auto &mp = state.processes[idx];
      pid      = mp.pid;
      injected = mp.injected;
      auto it  = state.local.find(pid);
      if (it != state.local.end()) selected = it->second.selected;
      exePath  = mp.exePath;
    }

    enum : UINT {
      ID_TOGGLE      = 5001,
      ID_UNINJECT    = 5002,
      ID_COPY_PID    = 5003,
      ID_OPEN_FOLDER = 5004,
    };

    HWND hwnd = FindWindowW(nullptr, L"OVson");
    if (!hwnd) return;
    HMENU menu = CreatePopupMenu();
    if (!menu) return;

    if (injected) {
      AppendMenuW(menu, MF_STRING, ID_UNINJECT, L"Uninject");
    } else {
      AppendMenuW(menu, MF_STRING, ID_TOGGLE,
                  selected ? L"Deselect" : L"Select for injection");
    }
    AppendMenuW(menu, MF_SEPARATOR, 0, nullptr);
    AppendMenuW(menu, MF_STRING, ID_COPY_PID, L"Copy PID");
    AppendMenuW(menu, MF_STRING | (exePath.empty() ? MF_GRAYED : 0),
                ID_OPEN_FOLDER, L"Open game folder");

    POINT pt;
    GetCursorPos(&pt);
    SetForegroundWindow(hwnd);
    UINT cmd = TrackPopupMenu(menu,
                              TPM_RETURNCMD | TPM_RIGHTBUTTON
                                | TPM_NONOTIFY,
                              pt.x, pt.y, 0, hwnd, nullptr);
    DestroyMenu(menu);

    switch (cmd) {
      case ID_TOGGLE:
        uiHandle->invoke_toggle_row(idx);
        break;
      case ID_UNINJECT:
        uiHandle->invoke_uninject_row(idx);
        break;
      case ID_COPY_PID: {
        wchar_t buf[16];
        wsprintfW(buf, L"%lu", (unsigned long)pid);
        if (OpenClipboard(hwnd)) {
          EmptyClipboard();
          size_t bytes = (wcslen(buf) + 1) * sizeof(wchar_t);
          HGLOBAL mem = GlobalAlloc(GMEM_MOVEABLE, bytes);
          if (mem) {
            void *p = GlobalLock(mem);
            if (p) {
              memcpy(p, buf, bytes);
              GlobalUnlock(mem);
              SetClipboardData(CF_UNICODETEXT, mem);
            } else {
              GlobalFree(mem);
            }
          }
          CloseClipboard();
        }
        break;
      }
      case ID_OPEN_FOLDER: {
        if (exePath.empty()) break;
        std::wstring arg = L"/select,\"" + exePath + L"\"";
        ShellExecuteW(nullptr, L"open", L"explorer.exe", arg.c_str(),
                      nullptr, SW_SHOWNORMAL);
        break;
      }
      default: break;
    }
  });

  ui->on_uninject_row([&](int idx) {
    if (g_shutdown.stopping()) return;
    loaderLog("on_uninject_row called with idx=%d", idx);
    DWORD pid = 0;
    {
      std::lock_guard<std::mutex> lk(state.mtx);
      if (idx < 0 || idx >= (int)state.processes.size()) {
        loaderLog("on_uninject_row: idx out of range, returning");
        return;
      }
      auto &mp = state.processes[idx];
      if (!mp.injected) {
        loaderLog("on_uninject_row: process not injected, returning");
        return;
      }
      pid = mp.pid;
      auto &lr = state.local[pid];
      lr.working = true;
      lr.finishedFail = false;
      lr.finishedOk = false;
      lr.stage = L"Uninjecting";
      lr.progress = 50;
    }
    loaderLog("on_uninject_row: calling publishProcesses for pid=%lu", pid);
    publishProcesses(*ui, state);
    loaderLog("on_uninject_row: publishProcesses done, spawning uninject thread");

    g_workers.start([uiHandle = ui, &state, pid]() {
      loaderLog("uninject thread started for pid=%lu", pid);
      DWORD err = 0;
      bool ok = uninjectPid(pid, &err);
      loaderLog("uninjectPid returned ok=%d err=%lu for pid=%lu", ok, err, pid);
      {
        std::lock_guard<std::mutex> lk(state.mtx);
        auto &lr = state.local[pid];
        lr.selected = false;
        lr.finishedOk = false;
        lr.finishedFail = !ok;
        lr.working = false;
        lr.progress = ok ? 0 : 100;
        if (ok) {
          lr.stage.clear();
        } else {
          wchar_t buf[96];
          const wchar_t *kind =
              err == 2  ? L"event missing"
            : err == 5  ? L"access denied"
                        : L"err";
          wsprintfW(buf, L"Uninject failed (%s, %lu)", kind, err);
          lr.stage = buf;
        }
        if (ok) {
          for (auto &mp : state.processes) {
            if (mp.pid == pid) {
              mp.injected = false;
              break;
            }
          }
        }
      }
      loaderLog("uninject thread: calling onUiThread for publishProcesses");
      onUiThread([uiHandle, &state]() mutable {
        loaderLog("uninject thread: onUiThread callback executing publishProcesses");
        publishProcesses(*uiHandle, state);
        loaderLog("uninject thread: publishProcesses done inside onUiThread");
      });
      loaderLog("uninject thread: finished for pid=%lu", pid);
    });
    loaderLog("on_uninject_row: worker registered");
  });
  ui->on_inject_clicked([&]() {
    if (!payloadOk || g_shutdown.stopping()) return;
    std::vector<DWORD> targets;
    {
      std::lock_guard<std::mutex> lk(state.mtx);
      for (auto &kv : state.local) {
        kv.second.finishedFail = false;
        if (!kv.second.working) kv.second.stage.clear();
      }
      for (const auto &mp : state.processes) {
        auto &lr = state.local[mp.pid];
        if (lr.selected && !mp.injected && !lr.working) {
          targets.push_back(mp.pid);
          lr.working = true;
          lr.finishedOk = false;
          lr.finishedFail = false;
          lr.progress = 1;
          lr.stage = L"Starting";
        }
      }
      if (targets.empty()) return;
      state.phase.store(kPhaseInjecting);
    }
    ui->set_phase(kPhaseInjecting);
    publishProcesses(*ui, state);

    for (DWORD pid : targets) {
      g_workers.start([uiHandle = ui, &state, pid]() mutable {
        auto progress = [uiHandle, &state, pid](int pct,
                                                const std::wstring &stage) mutable {
          {
            std::lock_guard<std::mutex> lk(state.mtx);
            auto &lr = state.local[pid];
            lr.progress = pct;
            lr.stage = stage;
          }
          onUiThread([uiHandle, &state]() mutable {
            publishProcesses(*uiHandle, state);
          });
        };
        bool ok = injectPid(pid, progress);
        {
          std::lock_guard<std::mutex> lk(state.mtx);
          auto &lr = state.local[pid];
          lr.working = false;
          if (ok) {
            lr.finishedOk = true;
            lr.selected = false;
            for (auto &mp : state.processes) {
              if (mp.pid == pid) {
                mp.injected = true;
                break;
              }
            }
          }
          else    lr.finishedFail = true;
          lr.progress = 100;
        }
        onUiThread([uiHandle, &state]() mutable {
          publishProcesses(*uiHandle, state);
        });
      });
    }
  });

  if (!payloadOk) {
    state.phase.store(kPhaseFailed);
    ui->set_phase(kPhaseFailed);
    ui->set_status_text(slint::SharedString(
        "Payload missing — please reinstall the loader."));
  }

  loaderLog("Calling ui->show()...");
  ui->show();
  loaderLog("ui->show() called.");

  slint::invoke_from_event_loop([]() {
    if (g_shutdown.stopping()) return;
    HWND hwnd = getSlintHwnd();
    loaderLog("slint invoke_from_event_loop: getSlintHwnd() returned hwnd=%p", hwnd);
    if (hwnd) {
      SetWindowSubclass(hwnd, SubclassProc, 1, 0);

      Tray::install(
          hwnd,
          /*onShow=*/[hwnd]() {
            if (g_shutdown.stopping()) return;
            ShowWindow(hwnd, SW_SHOW);
            ShowWindow(hwnd, SW_RESTORE);
            SetForegroundWindow(hwnd);
          },
          /*onQuit=*/[hwnd]() {
            requestLoaderShutdown(hwnd, "tray-quit");
          });

      int screenWidth = GetSystemMetrics(SM_CXSCREEN);
      int screenHeight = GetSystemMetrics(SM_CYSCREEN);
      RECT rc;
      GetWindowRect(hwnd, &rc);
      int wWidth = rc.right - rc.left;
      int wHeight = rc.bottom - rc.top;
      int x = (screenWidth - wWidth) / 2;
      int y = (screenHeight - wHeight) / 2;
      SetWindowPos(hwnd, nullptr, x, y, 0, 0, SWP_NOZORDER | SWP_NOSIZE | SWP_NOACTIVATE);

      g_showWatcherThread = std::thread([hwnd]() {
        loaderLog("ShowWatcher thread started (hwnd=%p)", hwnd);
        while (!g_stopShowWatcher.load()) {
          DWORD result = WaitForSingleObject(g_showWindowEvent, 500);
          if (result == WAIT_OBJECT_0) {
            if (g_stopShowWatcher.load() || g_shutdown.stopping()) break;
            loaderLog("ShowWatcher: event signaled, bringing window to front");
            ShowWindow(hwnd, SW_SHOW);
            ShowWindow(hwnd, SW_RESTORE);
            SetForegroundWindow(hwnd);
            FLASHWINFO fi = {};
            fi.cbSize = sizeof(fi);
            fi.hwnd = hwnd;
            fi.dwFlags = FLASHW_ALL | FLASHW_TIMERNOFG;
            fi.uCount = 3;
            fi.dwTimeout = 0;
            FlashWindowEx(&fi);
          }
        }
        loaderLog("ShowWatcher thread exiting");
      });
    }
  });

  /*
  slint::invoke_from_event_loop([uiHandle = ui, logModelPtr]() mutable {
    s_tail.start(
        ... (omitted) ...
    });
  */

  std::set_terminate([]() {
    loaderLog("FATAL: std::terminate() called!");
    try { throw; } catch (const std::exception& e) {
      loaderLog("FATAL: terminate reason: %s", e.what());
    } catch (...) {
      loaderLog("FATAL: terminate reason: unknown exception");
    }
    std::abort();
  });

  signal(SIGABRT, [](int) {
    loaderLog("FATAL: SIGABRT received!");
  });

  loaderLog("Entering slint::run_event_loop()...");
  slint::run_event_loop();
  if (!g_shutdown.stopping())
    requestLoaderShutdown(getSlintHwnd(), "event-loop-return");
  g_shutdown.advance(ShutdownCoordinator::Stage::EventLoopExited);
  loaderLog("Shutdown stage: %s",
            shutdownStageName(g_shutdown.stage()));

  loaderLog("Shutdown: signaling process scanner");
  stopScan.store(true);
  if (g_shutdownEvent) SetEvent(g_shutdownEvent);
  if (scanThread.joinable()) scanThread.join();
  g_shutdown.advance(ShutdownCoordinator::Stage::ScanStopped);
  loaderLog("Shutdown stage: %s",
            shutdownStageName(g_shutdown.stage()));

  loaderLog("Shutdown: stopping log tail, updater, and owned workers");
  s_tail.stop();
  Updater::shutdown();
  g_workers.joinAll();
  shutdownInjector();
  g_shutdown.advance(ShutdownCoordinator::Stage::WorkersStopped);
  loaderLog("Shutdown stage: %s",
            shutdownStageName(g_shutdown.stage()));

  loaderLog("Shutdown: removing tray icon and window subclasses");
  Tray::uninstall();
  if (HWND hwnd = getSlintHwnd(); hwnd && IsWindow(hwnd))
    RemoveWindowSubclass(hwnd, SubclassProc, 1);
  g_shutdown.advance(ShutdownCoordinator::Stage::TrayRemoved);
  loaderLog("Shutdown stage: %s",
            shutdownStageName(g_shutdown.stage()));

  g_stopShowWatcher.store(true);
  if (g_showWindowEvent) SetEvent(g_showWindowEvent); // wake the watcher so it can exit
  if (g_showWatcherThread.joinable()) g_showWatcherThread.join();
  g_shutdown.advance(ShutdownCoordinator::Stage::WatcherStopped);
  loaderLog("Shutdown stage: %s",
            shutdownStageName(g_shutdown.stage()));

  if (g_showWindowEvent) { CloseHandle(g_showWindowEvent); g_showWindowEvent = nullptr; }
  if (g_singleInstanceMutex) { CloseHandle(g_singleInstanceMutex); g_singleInstanceMutex = nullptr; }
  if (g_shutdownEvent) { CloseHandle(g_shutdownEvent); g_shutdownEvent = nullptr; }
  g_shutdown.advance(ShutdownCoordinator::Stage::HandlesClosed);
  loaderLog("Shutdown stage: %s",
            shutdownStageName(g_shutdown.stage()));
  g_shutdown.advance(ShutdownCoordinator::Stage::Complete);
  loaderLog("Shutdown complete. Loader exit does not imply DLL unload.");
  return 0;
}
